// frontend/src/app/components/sidebar/sidebar.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [CommonModule, RouterLink, RouterLinkActive],
  templateUrl: './sidebar.component.html',
  styleUrls: []
})
export class SidebarComponent {
  routes = [
    {
      label: 'Dashboard',
      iconPath: 'M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6',
      href: '/'
    },
    {
      label: 'Ejecución de Gastos',
      iconPath: 'M13 17h8m0 0V9m0 8l-8-8-4 4-6-6',
      href: '/gastos'
    },
    {
      label: 'Ejecución de Ingresos',
      iconPath: 'M13 7h8m0 0v8m0-8l-8 8-4-4-6 6',
      href: '/ingresos'
    },
    {
      label: 'Notas de Pago',
      iconPath: 'M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v8a3 3 0 003 3z',
      href: '/pagos'
    },
    {
      label: 'Reportes Presupuestales',
      iconPath: 'M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z',
      href: '/reportes'
    }
  ];
}

<div class="pb-12 min-h-screen border-r border-slate-800 bg-[#070f1e]/85 backdrop-blur-md text-white w-64 fixed flex flex-col justify-between">
  <div class="px-3 py-6 flex-1">
    <!-- Institutional Logo Section -->
    <div class="flex items-center pl-3 mb-10 gap-3">
      <div class="h-10 w-10 rounded-lg bg-gradient-to-br from-[#d40000] to-red-800 flex items-center justify-center shadow-lg shadow-red-900/30">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="h-6 w-6 text-white">
          <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 21h16.5M4.5 3h15M5.25 3v18m13.5-18v18M9 6.75h1.5m-1.5 3h1.5m-1.5 3h1.5m3-6H15m-1.5 3H15m-1.5 3H15M9 21v-3.375c0-.621.504-1.125 1.125-1.125h3.75c.621 0 1.125.504 1.125 1.125V21" />
        </svg>
      </div>
      <div>
        <h2 class="text-sm font-bold tracking-wider uppercase text-white leading-tight">
          SWSiconis <span class="text-[#d40000]">2026</span>
        </h2>
        <p class="text-[10px] text-slate-400 font-medium">HUANCABAMBA — PIURA</p>
      </div>
    </div>

    <!-- Navigation Routes using New Control Flow -->
    <div class="space-y-1">
      @for (route of routes; track route.href) {
        <a
          [routerLink]="route.href"
          routerLinkActive="active-route"
          [routerLinkActiveOptions]="{ exact: route.href === '/' }"
          #rla="routerLinkActive"
          class="text-sm group flex p-3 w-full justify-start font-medium cursor-pointer rounded-lg transition-all duration-300 relative overflow-hidden"
          [ngClass]="rla.isActive 
            ? 'bg-gradient-to-r from-red-950/40 to-[#d40000]/10 text-white font-semibold border-l-4 border-[#d40000] pl-2' 
            : 'text-slate-400 hover:text-white hover:bg-slate-800/35 hover:pl-4'"
        >
          <div class="flex items-center flex-1 gap-3 z-10">
            <svg 
              xmlns="http://www.w3.org/2000/svg" 
              fill="none" 
              viewBox="0 0 24 24" 
              stroke-width="2" 
              stroke="currentColor" 
              class="h-5 w-5 transition-colors duration-300"
              [ngClass]="rla.isActive ? 'text-[#d40000]' : 'text-slate-400 group-hover:text-white'"
            >
              <path stroke-linecap="round" stroke-linejoin="round" [attr.d]="route.iconPath" />
            </svg>
            {{ route.label }}
          </div>
          
          <!-- Subtle hover background highlight -->
          <div 
            class="absolute inset-0 bg-gradient-to-r from-red-600/0 via-red-600/0 to-red-600/0 transition-all duration-500 group-hover:from-red-600/5"
            [ngClass]="rla.isActive ? 'from-red-600/10' : ''"
          ></div>
        </a>
      }
    </div>
  </div>

  <!-- Footer / User info -->
  <div class="px-6 py-4 border-t border-slate-800/60 bg-black/20">
    <div class="flex items-center gap-3">
      <div class="h-8 w-8 rounded-full bg-slate-800 border border-slate-700 flex items-center justify-center text-xs font-bold text-slate-300 shadow-inner">
        UE
      </div>
      <div class="overflow-hidden">
        <h4 class="text-xs font-semibold text-slate-200 truncate">Gobierno Local</h4>
        <p class="text-[10px] text-slate-500 truncate">MPH - Piura</p>
      </div>
    </div>
  </div>
</div>

// backup-nextjs/src/components/sidebar.tsx
'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { cn } from '@/lib/utils';
import { 
  LayoutDashboard, 
  TrendingUp, 
  TrendingDown, 
  FileText, 
  CreditCard,
  Building2
} from 'lucide-react';

export function Sidebar({ className }: React.HTMLAttributes<HTMLDivElement>) {
  const pathname = usePathname();

  const routes = [
    {
      label: 'Dashboard',
      icon: LayoutDashboard,
      href: '/',
      active: pathname === '/',
    },
    {
      label: 'Ejecución de Gastos',
      icon: TrendingDown,
      href: '/gastos',
      active: pathname === '/gastos',
    },
    {
      label: 'Ejecución de Ingresos',
      icon: TrendingUp,
      href: '/ingresos',
      active: pathname === '/ingresos',
    },
    {
      label: 'Notas de Pago',
      icon: CreditCard,
      href: '/pagos',
      active: pathname === '/pagos',
    },
    {
      label: 'Reportes Presupuestales',
      icon: FileText,
      href: '/reportes',
      active: pathname === '/reportes',
    },
  ];

  return (
    <div className={cn("pb-12 min-h-screen border-r border-slate-800 bg-[#070f1e]/85 backdrop-blur-md text-white w-64 fixed flex flex-col justify-between", className)}>
      <div className="px-3 py-6 flex-1">
        {/* Institutional Logo Section */}
        <div className="flex items-center pl-3 mb-10 gap-3">
          <div className="h-10 w-10 rounded-lg bg-gradient-to-br from-[#d40000] to-red-800 flex items-center justify-center shadow-lg shadow-red-900/30">
            <Building2 className="h-6 w-6 text-white" />
          </div>
          <div>
            <h2 className="text-sm font-bold tracking-wider uppercase text-white leading-tight">
              SWSiconis <span className="text-[#d40000]">2026</span>
            </h2>
            <p className="text-[10px] text-slate-400 font-medium">HUANCABAMBA — PIURA</p>
          </div>
        </div>

        {/* Navigation Routes */}
        <div className="space-y-1">
          {routes.map((route) => (
            <Link
              key={route.href}
              href={route.href}
              className={cn(
                "text-sm group flex p-3 w-full justify-start font-medium cursor-pointer rounded-lg transition-all duration-300 relative overflow-hidden",
                route.active 
                  ? "bg-gradient-to-r from-red-950/40 to-[#d40000]/10 text-white font-semibold border-l-4 border-[#d40000] pl-2" 
                  : "text-slate-400 hover:text-white hover:bg-slate-800/35 hover:pl-4"
              )}
            >
              <div className="flex items-center flex-1 gap-3 z-10">
                <route.icon className={cn("h-5 w-5 transition-colors duration-300", 
                  route.active ? "text-[#d40000]" : "text-slate-400 group-hover:text-white"
                )} />
                {route.label}
              </div>
              
              {/* Subtle hover background highlight */}
              <div className={cn(
                "absolute inset-0 bg-gradient-to-r from-red-600/0 via-red-600/0 to-red-600/0 transition-all duration-500 group-hover:from-red-600/5",
                route.active && "from-red-600/10"
              )} />
            </Link>
          ))}
        </div>
      </div>

      {/* Footer / User info */}
      <div className="px-6 py-4 border-t border-slate-800/60 bg-black/20">
        <div className="flex items-center gap-3">
          <div className="h-8 w-8 rounded-full bg-slate-800 border border-slate-700 flex items-center justify-center text-xs font-bold text-slate-300 shadow-inner">
            UE
          </div>
          <div className="overflow-hidden">
            <h4 className="text-xs font-semibold text-slate-200 truncate">Gobierno Local</h4>
            <p className="text-[10px] text-slate-500 truncate">MPH - Piura</p>
          </div>
        </div>
      </div>
    </div>
  );
}
