// frontend/src/app/pages/gastos/gastos.component.ts
import { Component, OnInit, signal, computed, effect } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../services/api.service';
import { GastoRow, RubroOption } from '../../models/api.models';
import * as XLSX from 'xlsx';

@Component({
  selector: 'app-gastos',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './gastos.component.html',
  styleUrls: []
})
export class GastosComponent implements OnInit {
  loading = signal(true);
  rows = signal<GastoRow[]>([]);
  rubrosList = signal<RubroOption[]>([]);
  
  // Filters
  filterRubro = signal('');
  filterClasificador = signal('');
  searchQuery = signal('');

  // Expanded rows state (using record dictionary for row tracking: 'rubro-clasificador')
  expandedRows = signal<Record<string, boolean>>({});

  // Pagination
  currentPage = signal(1);
  pageSize = signal(10);

  // Computeds
  filteredRows = computed(() => {
    const list = this.rows();
    const query = this.searchQuery().toLowerCase().trim();
    if (!query) return list;

    return list.filter(row => 
      row.clasificador.toLowerCase().includes(query) ||
      (row.clasificador_nombre && row.clasificador_nombre.toLowerCase().includes(query)) ||
      (row.rubro_nombre && row.rubro_nombre.toLowerCase().includes(query))
    );
  });

  totals = computed(() => {
    const list = this.filteredRows();
    return list.reduce((acc, row) => {
      acc.pia += row.pia || 0;
      acc.pim += row.pim || 0;
      acc.certificado += row.certificado || 0;
      acc.comprometido += row.comprometido || 0;
      acc.devengado_total += row.devengado_total || 0;
      acc.girado_total += row.girado_total || 0;
      return acc;
    }, { pia: 0, pim: 0, certificado: 0, comprometido: 0, devengado_total: 0, girado_total: 0 });
  });

  paginatedRows = computed(() => {
    const list = this.filteredRows();
    const start = (this.currentPage() - 1) * this.pageSize();
    return list.slice(start, start + this.pageSize());
  });

  totalPages = computed(() => {
    const total = this.filteredRows().length;
    return Math.ceil(total / this.pageSize()) || 1;
  });

  monthsHeader = [
    'Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 
    'Jul', 'Ago', 'Set', 'Oct', 'Nov', 'Dic'
  ];

  constructor(private apiService: ApiService) {
    // Reload data on filter change
    effect(() => {
      this.fetchGastos();
      this.currentPage.set(1); // Reset page on filter changes
    }, { allowSignalWrites: true });
  }

  ngOnInit(): void {}

  fetchGastos(): void {
    this.loading.set(true);
    this.apiService.getGastos(this.filterRubro(), this.filterClasificador()).subscribe({
      next: (data) => {
        if (data.success) {
          this.rows.set(data.rows || []);
          if (data.rubros && this.rubrosList().length === 0) {
            this.rubrosList.set(data.rubros);
          }
        }
        this.loading.set(false);
      },
      error: (error) => {
        console.error('Error fetching gastos:', error);
        this.loading.set(false);
      }
    });
  }

  toggleRow(rubro: string, clasificador: string): void {
    const key = `${rubro}-${clasificador}`;
    const current = { ...this.expandedRows() };
    current[key] = !current[key];
    this.expandedRows.set(current);
  }

  isExpanded(rubro: string, clasificador: string): boolean {
    return !!this.expandedRows()[`${rubro}-${clasificador}`];
  }

  toggleAllRows(): void {
    const paginated = this.paginatedRows();
    const current = this.expandedRows();
    const allExpanded = paginated.every(r => current[`${r.rubro}-${r.clasificador}`]);

    if (allExpanded) {
      // Collapse all on current page
      const updated = { ...current };
      paginated.forEach(r => {
        delete updated[`${r.rubro}-${r.clasificador}`];
      });
      this.expandedRows.set(updated);
    } else {
      // Expand all on current page
      const updated = { ...current };
      paginated.forEach(r => {
        updated[`${r.rubro}-${r.clasificador}`] = true;
      });
      this.expandedRows.set(updated);
    }
  }

  formatMoney(val: number): string {
    return new Intl.NumberFormat('es-PE', {
      style: 'currency',
      currency: 'PEN',
      minimumFractionDigits: 2,
    }).format(val || 0);
  }

  exportToExcel(): void {
    const exportData = this.filteredRows().map((row) => ({
      'Rubro': row.rubro,
      'Nombre Rubro': row.rubro_nombre || '',
      'Clasificador': row.clasificador,
      'Nombre Clasificador': row.clasificador_nombre || '',
      'PIA (S/)': row.pia,
      'PIM (S/)': row.pim,
      'Certificado (S/)': row.certificado,
      'Comprometido (S/)': row.comprometido,
      'Devengado Total (S/)': row.devengado_total,
      'Girado Total (S/)': row.girado_total,
      'Avance Devengado (%)': row.pim > 0 ? ((row.devengado_total / row.pim) * 100).toFixed(2) : '0.00',
      'Avance Girado (%)': row.pim > 0 ? ((row.girado_total / row.pim) * 100).toFixed(2) : '0.00',
      // Monthly devengados
      'Dev Ene': row.dev_01, 'Dev Feb': row.dev_02, 'Dev Mar': row.dev_03, 'Dev Abr': row.dev_04,
      'Dev May': row.dev_05, 'Dev Jun': row.dev_06, 'Dev Jul': row.dev_07, 'Dev Ago': row.dev_08,
      'Dev Set': row.dev_09, 'Dev Oct': row.dev_10, 'Dev Nov': row.dev_11, 'Dev Dic': row.dev_12,
      // Monthly girados
      'Gir Ene': row.gir_01, 'Gir Feb': row.gir_02, 'Gir Mar': row.gir_03, 'Gir Abr': row.gir_04,
      'Gir May': row.gir_05, 'Gir Jun': row.gir_06, 'Gir Jul': row.gir_07, 'Gir Ago': row.gir_08,
      'Gir Set': row.gir_09, 'Gir Oct': row.gir_10, 'Gir Nov': row.gir_11, 'Gir Dic': row.gir_12,
    }));

    const worksheet = XLSX.utils.json_to_sheet(exportData);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Ejecución Gastos');
    
    // Auto-fit column widths
    const maxLens = Object.keys(exportData[0] || {}).map(key => {
      let maxLen = key.length;
      exportData.forEach(row => {
        const val = row[key as keyof typeof row];
        if (val !== null && val !== undefined) {
          maxLen = Math.max(maxLen, String(val).length);
        }
      });
      return { wch: maxLen + 2 };
    });
    worksheet['!cols'] = maxLens;

    XLSX.writeFile(workbook, `SWSiconis_Ejecucion_Gastos_${new Date().getFullYear()}.xlsx`);
  }

  changePage(dir: number): void {
    const next = this.currentPage() + dir;
    if (next >= 1 && next <= this.totalPages()) {
      this.currentPage.set(next);
    }
  }
}

<div class="space-y-8 animate-in">
  
  <!-- Header Area -->
  <div class="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-800/60 pb-6">
    <div>
      <div class="flex items-center gap-2 text-[#d40000] text-xs font-bold uppercase tracking-widest mb-1">
        <!-- Trending Down Icon SVG -->
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="h-4 w-4">
          <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
        </svg>
        Módulo de Presupuesto
      </div>
      <h1 class="text-2xl md:text-3xl font-extrabold text-white tracking-tight leading-none">
        Ejecución de Gastos
      </h1>
      <p class="text-slate-400 text-xs mt-1 font-medium">
        Seguimiento detallado de PIA, PIM, Certificaciones y la evolución mensual de Devengados y Girados.
      </p>
    </div>

    <div class="flex items-center gap-3">
      <button 
        (click)="exportToExcel()"
        [disabled]="loading() || filteredRows().length === 0"
        class="flex items-center gap-2 text-xs font-bold px-4 py-2.5 rounded-lg border border-emerald-800/60 bg-emerald-950/40 hover:bg-emerald-900/40 text-emerald-400 hover:text-emerald-300 transition-all duration-300 disabled:opacity-50 disabled:cursor-not-allowed shadow-md shadow-emerald-950/20"
      >
        <!-- FileSpreadsheet Icon SVG -->
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="h-4 w-4">
          <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m6.75 12H9m1.5-12H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" />
        </svg>
        Exportar Excel
      </button>
      
      <button 
        (click)="fetchGastos()"
        class="flex items-center justify-center p-2.5 rounded-lg border border-slate-800 bg-[#0b1329]/40 hover:bg-slate-800/40 text-slate-300 hover:text-white transition-all duration-300 backdrop-blur-sm"
        title="Actualizar datos"
      >
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2.5" stroke="currentColor" class="h-4 w-4" [ngClass]="{'animate-spin': loading()}">
          <path stroke-linecap="round" stroke-linejoin="round" d="M16.023 9.348h4.992v-.001M2.985 19.644v-4.992m0 0h4.992m-4.993 0l3.181 3.183a8.25 8.25 0 0013.803-3.7M4.031 9.865a8.25 8.25 0 0113.803-3.7l3.181 3.182m0-4.991v4.99" />
        </svg>
      </button>
    </div>
  </div>

  <!-- Interactive Filters Panel -->
  <div class="p-5 rounded-2xl border border-slate-800/70 bg-[#091122]/40 backdrop-blur-md shadow-lg shadow-black/20 flex flex-col gap-4">
    <div class="flex items-center gap-2 text-xs font-bold text-slate-300 uppercase tracking-wider">
      <!-- Sliders Icon SVG -->
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="h-4 w-4 text-[#d40000]">
        <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 6h9.75M10.5 6a1.5 1.5 0 11-3 0m3 0a1.5 1.5 0 10-3 0M3.75 6H7.5m3 12h9.75m-9.75 0a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m-3.75 0H7.5m9-6h3.75m-3.75 0a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m-9.75 0h9.75" />
      </svg>
      Filtros y Búsqueda
    </div>

    <div class="grid grid-cols-1 sm:grid-cols-3 gap-4">
      <!-- Rubro Selector -->
      <div class="space-y-1.5">
        <label class="text-[10px] uppercase font-bold text-slate-500 tracking-wider flex items-center gap-1.5">
          <!-- Layers Icon SVG -->
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="h-3.5 w-3.5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6.429 9.75L2.25 12l4.179 2.25m11.142 0L21.75 12l-4.179-2.25m-11.142 0L10.5 7.5 12 6.75l1.5.75 4.179 2.25m-11.142 0L12 12l5.571-2.25M6.429 14.25L12 16.5l5.571-2.25M12 16.5v4.5m-3.75-2.25h7.5" />
          </svg>
          Rubro (Fuente Financiamiento)
        </label>
        <select
          [ngModel]="filterRubro()"
          (ngModelChange)="filterRubro.set($event)"
          class="w-full text-xs bg-[#0b1428] border border-slate-800/80 rounded-xl px-3.5 py-2.5 text-slate-300 focus:outline-none focus:border-[#d40000]/60 transition-all duration-300"
        >
          <option value="">Todos los Rubros</option>
          @for (r of rubrosList(); track r.codigo) {
            <option [value]="r.codigo">{{ r.codigo }} - {{ r.nombre }}</option>
          }
        </select>
      </div>

      <!-- Clasificador Filter -->
      <div class="space-y-1.5">
        <label class="text-[10px] uppercase font-bold text-slate-500 tracking-wider flex items-center gap-1.5">
          <!-- Calendar Icon SVG -->
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="h-3.5 w-3.5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 012.25-2.25h13.5A2.25 2.25 0 0121 7.5v11.25m-18 0A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75m-18 0v-7.5A2.25 2.25 0 015.25 9h13.5A2.25 2.25 0 0121 11.25v7.5" />
          </svg>
          Nivel Clasificador (Prefijo)
        </label>
        <input
          type="text"
          placeholder="Ej: 2.6 o 2.3..."
          [ngModel]="filterClasificador()"
          (ngModelChange)="filterClasificador.set($event)"
          class="w-full text-xs bg-[#0b1428] border border-slate-800/80 rounded-xl px-3.5 py-2.5 text-slate-300 placeholder-slate-600 focus:outline-none focus:border-[#d40000]/60 transition-all duration-300"
        />
      </div>

      <!-- Text Search Filter -->
      <div class="space-y-1.5">
        <label class="text-[10px] uppercase font-bold text-slate-500 tracking-wider flex items-center gap-1.5">
          <!-- Search Icon SVG -->
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="h-3.5 w-3.5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
          </svg>
          Búsqueda por Nombre / Clasificador
        </label>
        <div class="relative">
          <input
            type="text"
            placeholder="Buscar coincidencia..."
            [ngModel]="searchQuery()"
            (ngModelChange)="searchQuery.set($event)"
            class="w-full text-xs bg-[#0b1428] border border-slate-800/80 rounded-xl pl-9 pr-3.5 py-2.5 text-slate-300 placeholder-slate-600 focus:outline-none focus:border-[#d40000]/60 transition-all duration-300"
          />
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="absolute left-3.5 top-3.5 h-3.5 w-3.5 text-slate-600">
            <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
          </svg>
        </div>
      </div>
    </div>
  </div>

  <!-- Summary Mini Cards -->
  <div class="grid grid-cols-2 md:grid-cols-4 gap-4">
    <div class="p-4 rounded-xl border border-slate-800/50 bg-[#091224]/20 backdrop-blur-md">
      <p class="text-[9px] uppercase font-bold text-slate-500 tracking-widest mb-1">PIM Total Filtrado</p>
      <p class="text-base font-extrabold text-white">{{ formatMoney(totals().pim) }}</p>
    </div>
    <div class="p-4 rounded-xl border border-slate-800/50 bg-[#091224]/20 backdrop-blur-md">
      <p class="text-[9px] uppercase font-bold text-slate-500 tracking-widest mb-1">Certificado Total</p>
      <p class="text-base font-extrabold text-blue-400">{{ formatMoney(totals().certificado) }}</p>
    </div>
    <div class="p-4 rounded-xl border border-slate-800/50 bg-[#091224]/20 backdrop-blur-md">
      <p class="text-[9px] uppercase font-bold text-red-400/80 tracking-widest mb-1">Devengado Total</p>
      <p class="text-base font-extrabold text-red-400">{{ formatMoney(totals().devengado_total) }}</p>
    </div>
    <div class="p-4 rounded-xl border border-slate-800/50 bg-[#091224]/20 backdrop-blur-md">
      <p class="text-[9px] uppercase font-bold text-slate-500 tracking-widest mb-1">% Avance (Dev/PIM)</p>
      <div class="flex items-center gap-2">
        <p class="text-base font-extrabold text-white">
          {{ (totals().pim > 0 ? (totals().devengado_total / totals().pim * 100) : 0).toFixed(1) }}%
        </p>
        <div class="flex-1 bg-slate-800 rounded-full h-1.5 overflow-hidden">
          <div 
            class="bg-red-600 h-full rounded-full" 
            [style.width.%]="totals().pim > 0 ? (totals().devengado_total / totals().pim * 100) : 0"
          ></div>
        </div>
      </div>
    </div>
  </div>

  <!-- Main Table Container -->
  <div class="rounded-2xl border border-slate-800/80 bg-[#081020]/60 backdrop-blur-md shadow-2xl overflow-hidden">
    <div class="overflow-x-auto">
      <table class="w-full text-left border-collapse">
        <thead>
          <tr class="border-b border-slate-800 bg-slate-900/35 text-slate-400 text-[10px] uppercase font-bold tracking-wider">
            <th class="py-4 px-5 w-12 text-center">
              <button 
                (click)="toggleAllRows()"
                class="p-1 rounded bg-slate-800/60 hover:bg-slate-700/60 transition-colors"
                title="Expandir/Contraer todos"
              >
                <!-- Chevron Down Icon -->
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2.5" stroke="currentColor" class="h-3.5 w-3.5 text-slate-300">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
                </svg>
              </button>
            </th>
            <th class="py-4 px-4 w-16 text-center">Rubro</th>
            <th class="py-4 px-4 w-32">Clasificador</th>
            <th class="py-4 px-4">Descripción</th>
            <th class="py-4 px-4 text-right">PIA</th>
            <th class="py-4 px-4 text-right">PIM</th>
            <th class="py-4 px-4 text-right">Certificado</th>
            <th class="py-4 px-4 text-right">Devengado</th>
            <th class="py-4 px-4 text-right">Girado</th>
            <th class="py-4 px-4 text-center w-28">% Avance</th>
          </tr>
        </thead>
        
        <tbody class="divide-y divide-slate-800/40 text-xs font-medium text-slate-300">
          @if (loading()) {
            @for (skele of [1,2,3,4,5]; track skele) {
              <tr class="animate-pulse">
                <td class="py-5 px-5"><div class="h-4 w-4 bg-slate-800 rounded mx-auto" /></td>
                <td class="py-5 px-4"><div class="h-4 w-8 bg-slate-800 rounded mx-auto" /></td>
                <td class="py-5 px-4"><div class="h-4 w-20 bg-slate-800 rounded" /></td>
                <td class="py-5 px-4"><div class="h-4 w-44 bg-slate-800 rounded" /></td>
                <td class="py-5 px-4"><div class="h-4 w-16 bg-slate-800 rounded ml-auto" /></td>
                <td class="py-5 px-4"><div class="h-4 w-16 bg-slate-800 rounded ml-auto" /></td>
                <td class="py-5 px-4"><div class="h-4 w-16 bg-slate-800 rounded ml-auto" /></td>
                <td class="py-5 px-4"><div class="h-4 w-16 bg-slate-800 rounded ml-auto" /></td>
                <td class="py-5 px-4"><div class="h-4 w-16 bg-slate-800 rounded ml-auto" /></td>
                <td class="py-5 px-4"><div class="h-4 w-12 bg-slate-800 rounded mx-auto" /></td>
              </tr>
            }
          } @else {
            @for (row of paginatedRows(); track row.rubro + '-' + row.clasificador) {
              <tr class="hover:bg-slate-900/40 transition-colors duration-200">
                <td class="py-4 px-5 text-center">
                  <button 
                    (click)="toggleRow(row.rubro, row.clasificador)"
                    class="p-1 rounded bg-slate-950/60 hover:bg-slate-800 border border-slate-800 transition-colors"
                  >
                    @if (isExpanded(row.rubro, row.clasificador)) {
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2.5" stroke="currentColor" class="h-3.5 w-3.5 text-[#d40000]">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 15.75l7.5-7.5 7.5 7.5" />
                      </svg>
                    } @else {
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2.5" stroke="currentColor" class="h-3.5 w-3.5 text-slate-400">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
                      </svg>
                    }
                  </button>
                </td>
                <td class="py-4 px-4 text-center font-bold text-slate-400">{{ row.rubro }}</td>
                <td class="py-4 px-4 font-mono font-bold text-[#d40000]">{{ row.clasificador }}</td>
                <td class="py-4 px-4 font-semibold text-slate-200">{{ row.clasificador_nombre || 'Sin descripción en clasificador' }}</td>
                <td class="py-4 px-4 text-right">{{ formatMoney(row.pia) }}</td>
                <td class="py-4 px-4 text-right text-slate-200 font-bold">{{ formatMoney(row.pim) }}</td>
                <td class="py-4 px-4 text-right text-blue-400">{{ formatMoney(row.certificado) }}</td>
                <td class="py-4 px-4 text-right text-red-400 font-bold">{{ formatMoney(row.devengado_total) }}</td>
                <td class="py-4 px-4 text-right text-emerald-400">{{ formatMoney(row.girado_total) }}</td>
                <td class="py-4 px-4">
                  <div class="flex items-center justify-center gap-2">
                    <span class="font-bold text-white">
                      {{ (row.pim > 0 ? (row.devengado_total / row.pim * 100) : 0).toFixed(1) }}%
                    </span>
                    <div class="w-12 bg-slate-800 rounded-full h-1 overflow-hidden hidden sm:block">
                      <div 
                        class="bg-gradient-to-r from-red-600 to-[#d40000] h-full" 
                        [style.width.%]="row.pim > 0 ? (row.devengado_total / row.pim * 100) : 0"
                      ></div>
                    </div>
                  </div>
                </td>
              </tr>

              <!-- Expanded Row Details for Monthly Breakdown -->
              @if (isExpanded(row.rubro, row.clasificador)) {
                <tr class="bg-[#050b16]/70 border-l-2 border-[#d40000]">
                  <td colspan="10" class="p-6">
                    <div class="space-y-4">
                      <div class="flex items-center gap-2 text-xs font-bold text-slate-400 uppercase tracking-wider">
                        <!-- Calendar Icon SVG -->
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="h-4 w-4 text-[#d40000]">
                          <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 3v2.25M17.25 3v2.25M3 18.75V7.5a2.25 2.25 0 012.25-2.25h13.5A2.25 2.25 0 0121 7.5v11.25m-18 0A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75m-18 0v-7.5A2.25 2.25 0 015.25 9h13.5A2.25 2.25 0 0121 11.25v7.5" />
                        </svg>
                        Distribución Mensual del Gasto — Año 2026
                      </div>
                      
                      <div class="overflow-x-auto rounded-xl border border-slate-800/40 bg-slate-950/40">
                        <table class="w-full text-center border-collapse">
                          <thead>
                            <tr class="border-b border-slate-800 text-[10px] text-slate-500 font-bold uppercase tracking-wider bg-black/15">
                              <th class="py-3 px-2 text-left pl-4 w-28">Etapa Gasto</th>
                              @for (month of monthsHeader; track month) {
                                <th class="py-3 px-2">{{ month }}</th>
                              }
                            </tr>
                          </thead>
                          <tbody class="divide-y divide-slate-800/20 text-[11px] font-semibold">
                            <!-- Devengado monthly values -->
                            <tr class="hover:bg-slate-900/10">
                              <td class="py-3 px-2 text-left pl-4 font-bold text-red-400">Devengado</td>
                              <td class="py-3 px-2">{{ formatMoney(row.dev_01) }}</td>
                              <td class="py-3 px-2">{{ formatMoney(row.dev_02) }}</td>
                              <td class="py-3 px-2">{{ formatMoney(row.dev_03) }}</td>
                              <td class="py-3 px-2">{{ formatMoney(row.dev_04) }}</td>
                              <td class="py-3 px-2">{{ formatMoney(row.dev_05) }}</td>
                              <td class="py-3 px-2">{{ formatMoney(row.dev_06) }}</td>
                              <td class="py-3 px-2">{{ formatMoney(row.dev_07) }}</td>
                              <td class="py-3 px-2">{{ formatMoney(row.dev_08) }}</td>
                              <td class="py-3 px-2">{{ formatMoney(row.dev_09) }}</td>
                              <td class="py-3 px-2">{{ formatMoney(row.dev_10) }}</td>
                              <td class="py-3 px-2">{{ formatMoney(row.dev_11) }}</td>
                              <td class="py-3 px-2">{{ formatMoney(row.dev_12) }}</td>
                            </tr>
                            <!-- Girado monthly values -->
                            <tr class="hover:bg-slate-900/10">
                              <td class="py-3 px-2 text-left pl-4 font-bold text-emerald-400">Girado</td>
                              <td class="py-3 px-2">{{ formatMoney(row.gir_01) }}</td>
                              <td class="py-3 px-2">{{ formatMoney(row.gir_02) }}</td>
                              <td class="py-3 px-2">{{ formatMoney(row.gir_03) }}</td>
                              <td class="py-3 px-2">{{ formatMoney(row.gir_04) }}</td>
                              <td class="py-3 px-2">{{ formatMoney(row.gir_05) }}</td>
                              <td class="py-3 px-2">{{ formatMoney(row.gir_06) }}</td>
                              <td class="py-3 px-2">{{ formatMoney(row.gir_07) }}</td>
                              <td class="py-3 px-2">{{ formatMoney(row.gir_08) }}</td>
                              <td class="py-3 px-2">{{ formatMoney(row.gir_09) }}</td>
                              <td class="py-3 px-2">{{ formatMoney(row.gir_10) }}</td>
                              <td class="py-3 px-2">{{ formatMoney(row.gir_11) }}</td>
                              <td class="py-3 px-2">{{ formatMoney(row.gir_12) }}</td>
                            </tr>
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </td>
                </tr>
              }
            }
          }
        </tbody>
      </table>
    </div>

    <!-- Table Footer / Pagination -->
    <div class="p-4 border-t border-slate-800 bg-slate-900/20 flex flex-col sm:flex-row items-center justify-between gap-4 text-xs font-semibold text-slate-400">
      <div>
        Mostrando registros del 
        <span class="text-white">{{ filteredRows().length === 0 ? 0 : (currentPage() - 1) * pageSize() + 1 }}</span> al 
        <span class="text-white">{{ Math.min(currentPage() * pageSize(), filteredRows().length) }}</span> de 
        <span class="text-white">{{ filteredRows().length }}</span> totales
      </div>

      <div class="flex items-center gap-2">
        <button 
          (click)="changePage(-1)" 
          [disabled]="currentPage() === 1 || loading()"
          class="p-2 rounded bg-slate-850 hover:bg-slate-800 border border-slate-800 disabled:opacity-30 disabled:cursor-not-allowed transition-colors"
        >
          <!-- Chevron Left Icon -->
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2.5" stroke="currentColor" class="h-3.5 w-3.5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5" />
          </svg>
        </button>
        
        <div class="px-3 py-1 bg-[#0b1329]/65 border border-slate-800 rounded text-slate-300 font-bold">
          Página {{ currentPage() }} de {{ totalPages() }}
        </div>
        
        <button 
          (click)="changePage(1)" 
          [disabled]="currentPage() === totalPages() || loading()"
          class="p-2 rounded bg-slate-850 hover:bg-slate-800 border border-slate-800 disabled:opacity-30 disabled:cursor-not-allowed transition-colors"
        >
          <!-- Chevron Right Icon -->
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2.5" stroke="currentColor" class="h-3.5 w-3.5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
          </svg>
        </button>
      </div>
    </div>
  </div>

</div>

// src/app/gastos/page.tsx
'use client';

import { useState, useEffect, useCallback, Fragment } from 'react';
import {
  TrendingDown,
  Search,
  FileSpreadsheet,
  ChevronDown,
  ChevronUp,
  RefreshCw,
  SlidersHorizontal,
  Layers,
  ChevronLeft,
  ChevronRight,
  AlertTriangle,
} from 'lucide-react';
import { cn } from '@/lib/utils';
import * as XLSX from 'xlsx';
import { PageHeader } from '@/components/ui/page-header';

interface GastoRow {
  rubro: string; rubro_nombre: string;
  clasificador: string; clasificador_nombre: string;
  pia: number; pim: number; certificado: number; comprometido: number;
  devengado_total: number; girado_total: number;
  dev_01: number; dev_02: number; dev_03: number; dev_04: number;
  dev_05: number; dev_06: number; dev_07: number; dev_08: number;
  dev_09: number; dev_10: number; dev_11: number; dev_12: number;
  gir_01: number; gir_02: number; gir_03: number; gir_04: number;
  gir_05: number; gir_06: number; gir_07: number; gir_08: number;
  gir_09: number; gir_10: number; gir_11: number; gir_12: number;
}

interface RubroOption { codigo: string; nombre: string; }

const formatMoney = (val: number) =>
  new Intl.NumberFormat('es-PE', {
    style: 'currency', currency: 'PEN', minimumFractionDigits: 2,
  }).format(val || 0);

const MONTHS = ['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Set','Oct','Nov','Dic'];

export default function GastosPage() {
  const [loading, setLoading] = useState(true);
  const [rows, setRows] = useState<GastoRow[]>([]);
  const [rubrosList, setRubrosList] = useState<RubroOption[]>([]);
  const [filterRubro, setFilterRubro] = useState('');
  const [filterClasificador, setFilterClasificador] = useState('');
  const [searchQuery, setSearchQuery] = useState('');
  const [expandedRows, setExpandedRows] = useState<Record<string, boolean>>({});
  const [currentPage, setCurrentPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  const [filterOpen, setFilterOpen] = useState(true);

  const fetchGastos = useCallback(async () => {
    setLoading(true);
    try {
      let url = '/api/gastos';
      const params = new URLSearchParams();
      if (filterRubro) params.append('rubro', filterRubro);
      if (filterClasificador) params.append('clasificador', filterClasificador);
      if (params.toString()) url += `?${params.toString()}`;
      const res = await fetch(url);
      const data = await res.json();
      if (data.success) {
        setRows(data.rows || []);
        if (data.rubros && rubrosList.length === 0) setRubrosList(data.rubros);
      }
    } catch (e) {
      console.error('Error:', e);
    } finally {
      setLoading(false);
    }
  }, [filterRubro, filterClasificador, rubrosList.length]);

  useEffect(() => { fetchGastos(); setCurrentPage(1); }, [fetchGastos]);

  const filteredRows = rows.filter((row) => {
    const q = searchQuery.toLowerCase().trim();
    if (!q) return true;
    return (
      row.clasificador.toLowerCase().includes(q) ||
      (row.clasificador_nombre && row.clasificador_nombre.toLowerCase().includes(q)) ||
      (row.rubro_nombre && row.rubro_nombre.toLowerCase().includes(q))
    );
  });

  const totals = filteredRows.reduce(
    (acc, row) => {
      acc.pia += row.pia || 0;
      acc.pim += row.pim || 0;
      acc.certificado += row.certificado || 0;
      acc.comprometido += row.comprometido || 0;
      acc.devengado_total += row.devengado_total || 0;
      acc.girado_total += row.girado_total || 0;
      return acc;
    },
    { pia: 0, pim: 0, certificado: 0, comprometido: 0, devengado_total: 0, girado_total: 0 }
  );

  const totalRecords = filteredRows.length;
  const totalPages = Math.ceil(totalRecords / pageSize) || 1;
  const startIndex = (currentPage - 1) * pageSize;
  const paginatedRows = filteredRows.slice(startIndex, startIndex + pageSize);

  const toggleRow = (id: string) =>
    setExpandedRows((prev) => ({ ...prev, [id]: !prev[id] }));

  const exportToExcel = () => {
    const data = filteredRows.map((row) => ({
      'Rubro': row.rubro, 'Nombre Rubro': row.rubro_nombre || '',
      'Clasificador': row.clasificador, 'Nombre Clasificador': row.clasificador_nombre || '',
      'PIA (S/)': row.pia, 'PIM (S/)': row.pim,
      'Certificado (S/)': row.certificado, 'Comprometido (S/)': row.comprometido,
      'Devengado Total (S/)': row.devengado_total, 'Girado Total (S/)': row.girado_total,
      'Avance Dev. (%)': row.pim > 0 ? ((row.devengado_total / row.pim) * 100).toFixed(2) : '0.00',
    }));
    const ws = XLSX.utils.json_to_sheet(data);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Ejecución Gastos');
    XLSX.writeFile(wb, `SWSiconis_Gastos_${new Date().getFullYear()}.xlsx`);
  };

  return (
    <div className="space-y-6 animate-fade-in">

      {/* Header */}
      <PageHeader
        sectionLabel="Módulo de Presupuesto"
        icon={TrendingDown}
        title="Ejecución de Gastos"
        description="Seguimiento detallado de PIA, PIM, Certificaciones y evolución mensual de Devengados y Girados."
        actions={
          <>
            <button
              onClick={exportToExcel}
              disabled={loading || filteredRows.length === 0}
              className="btn-excel"
            >
              <FileSpreadsheet className="h-3.5 w-3.5" />
              Exportar Excel
            </button>
            <button
              onClick={() => setFilterOpen(!filterOpen)}
              className={cn('btn-secondary', filterOpen && 'border-[#D40000]/40 text-white')}
            >
              <SlidersHorizontal className="h-3.5 w-3.5" />
              Filtros
            </button>
            <button onClick={fetchGastos} className="btn-secondary p-2">
              <RefreshCw className={cn('h-3.5 w-3.5', loading && 'animate-spin-smooth')} />
            </button>
          </>
        }
      />

      {/* Filter Panel */}
      {filterOpen && (
        <div className="filter-panel animate-fade-in grid grid-cols-1 sm:grid-cols-3 gap-4">
          <div className="space-y-1.5">
            <label className="flex items-center gap-1.5 text-[10px] font-700 uppercase tracking-widest text-[#4A6080]">
              <Layers className="h-3 w-3" /> Rubro
            </label>
            <select
              value={filterRubro}
              onChange={(e) => setFilterRubro(e.target.value)}
              className="form-select"
            >
              <option value="">Todos los Rubros</option>
              {rubrosList.map((r) => (
                <option key={r.codigo} value={r.codigo}>
                  {r.codigo} — {r.nombre}
                </option>
              ))}
            </select>
          </div>
          <div className="space-y-1.5">
            <label className="flex items-center gap-1.5 text-[10px] font-700 uppercase tracking-widest text-[#4A6080]">
              <Layers className="h-3 w-3" /> Clasificador (Prefijo)
            </label>
            <input
              type="text"
              placeholder="Ej: 2.6 o 2.3..."
              value={filterClasificador}
              onChange={(e) => setFilterClasificador(e.target.value)}
              className="form-input"
            />
          </div>
          <div className="space-y-1.5">
            <label className="flex items-center gap-1.5 text-[10px] font-700 uppercase tracking-widest text-[#4A6080]">
              <Search className="h-3 w-3" /> Búsqueda por Nombre
            </label>
            <div className="relative">
              <input
                type="text"
                placeholder="Buscar clasificador o descripción..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="form-input pl-8"
              />
              <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 h-3.5 w-3.5 text-[#4A6080]" />
            </div>
          </div>
        </div>
      )}

      {/* KPI Summary Row */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3 stagger-children">
        {[
          { label: 'PIM Total', value: totals.pim,              color: '#1565C0' },
          { label: 'Certificado', value: totals.certificado,    color: '#7C3AED' },
          { label: 'Devengado', value: totals.devengado_total,  color: '#D40000' },
          { label: '% Avance Dev.',
            value: totals.pim > 0 ? (totals.devengado_total / totals.pim) * 100 : 0,
            color: '#10B981', isPercent: true,
            progress: totals.pim > 0 ? (totals.devengado_total / totals.pim) * 100 : 0 },
        ].map((item) => (
          <div key={item.label} className="kpi-card !p-4">
            <p className="text-[9px] font-800 uppercase tracking-widest text-[#4A6080] mb-1.5">{item.label}</p>
            {(item as { isPercent?: boolean }).isPercent ? (
              <>
                <p className="text-lg font-black tabular-nums" style={{ color: item.color }}>
                  {item.value.toFixed(1)}%
                </p>
                <div className="progress-bar-track mt-2">
                  <div className="progress-bar-fill green" style={{ width: `${Math.min(item.value, 100)}%` }} />
                </div>
              </>
            ) : (
              <p className="text-base font-black tabular-nums" style={{ color: item.color }}>
                {new Intl.NumberFormat('es-PE', { style: 'currency', currency: 'PEN', maximumFractionDigits: 0 }).format(item.value)}
              </p>
            )}
          </div>
        ))}
      </div>

      {/* Main Table */}
      <div className="rounded-2xl border border-white/[0.06] bg-[#061526]/70 backdrop-blur-xl shadow-2xl overflow-hidden">
        <div className="overflow-x-auto">
          <table className="data-table">
            <thead>
              <tr>
                <th className="w-10 text-center">
                  <button
                    onClick={() => {
                      const allExp = paginatedRows.every(r => expandedRows[`${r.rubro}-${r.clasificador}`]);
                      if (allExp) {
                        setExpandedRows({});
                      } else {
                        const next: Record<string, boolean> = {};
                        paginatedRows.forEach(r => { next[`${r.rubro}-${r.clasificador}`] = true; });
                        setExpandedRows(next);
                      }
                    }}
                    className="p-1 rounded-md bg-white/[0.05] hover:bg-white/[0.08] transition-colors"
                    title="Expandir/Contraer todos"
                  >
                    <ChevronDown className="h-3.5 w-3.5 text-[#4A6080]" />
                  </button>
                </th>
                <th className="w-14 text-center">Rubro</th>
                <th className="w-32">Clasificador</th>
                <th>Descripción</th>
                <th className="text-right">PIA</th>
                <th className="text-right">PIM</th>
                <th className="text-right">Certif.</th>
                <th className="text-right">Devengado</th>
                <th className="text-right">Girado</th>
                <th className="text-center w-28">% Avance</th>
              </tr>
            </thead>
            <tbody>
              {loading ? (
                Array.from({ length: 7 }).map((_, i) => (
                  <tr key={i}>
                    {Array.from({ length: 10 }).map((__, j) => (
                      <td key={j}><div className="skeleton h-4 w-full" /></td>
                    ))}
                  </tr>
                ))
              ) : paginatedRows.length === 0 ? (
                <tr>
                  <td colSpan={10} className="py-16 text-center">
                    <div className="flex flex-col items-center gap-3 text-[#2A3A50]">
                      <AlertTriangle className="h-10 w-10" />
                      <p className="text-sm font-semibold">No se encontraron registros de ejecución de gastos.</p>
                    </div>
                  </td>
                </tr>
              ) : (
                paginatedRows.map((row) => {
                  const rowId = `${row.rubro}-${row.clasificador}`;
                  const isExpanded = !!expandedRows[rowId];
                  const avance = row.pim > 0 ? (row.devengado_total / row.pim) * 100 : 0;

                  return (
                    <Fragment key={rowId}>
                      <tr
                        className={cn(
                          'cursor-pointer transition-colors duration-150',
                          isExpanded && 'bg-white/[0.03] border-l-2 border-[#D40000]'
                        )}
                        onClick={() => toggleRow(rowId)}
                      >
                        <td className="text-center">
                          <span className="p-1 rounded hover:bg-white/10 transition-colors inline-flex">
                            {isExpanded ? (
                              <ChevronUp className="h-3.5 w-3.5 text-[#D40000]" />
                            ) : (
                              <ChevronDown className="h-3.5 w-3.5 text-[#4A6080]" />
                            )}
                          </span>
                        </td>
                        <td className="text-center font-bold text-[#4A6080]">{row.rubro}</td>
                        <td className="font-mono font-bold text-white tracking-wider text-[11px]">{row.clasificador}</td>
                        <td className="max-w-[220px]" title={row.clasificador_nombre}>
                          <p className="font-semibold text-[#D0D8E8] truncate text-[11px]">
                            {row.clasificador_nombre || 'Sin especificación'}
                          </p>
                          <p className="text-[9px] text-[#4A6080] truncate">{row.rubro_nombre}</p>
                        </td>
                        <td className="text-right font-mono text-[11px] text-[#4A6080]">{formatMoney(row.pia)}</td>
                        <td className="text-right font-mono font-semibold text-[11px] text-white">{formatMoney(row.pim)}</td>
                        <td className="text-right font-mono text-[11px] text-purple-400">{formatMoney(row.certificado)}</td>
                        <td className="text-right font-mono font-semibold text-[11px] text-red-400">{formatMoney(row.devengado_total)}</td>
                        <td className="text-right font-mono text-[11px] text-emerald-400">{formatMoney(row.girado_total)}</td>
                        <td className="text-center">
                          <div className="flex flex-col items-center gap-1">
                            <span className="font-bold font-mono text-[11px] text-white">{avance.toFixed(1)}%</span>
                            <div className="w-16 progress-bar-track">
                              <div
                                className={cn(
                                  'progress-bar-fill',
                                  avance >= 75 ? 'green' : avance >= 40 ? 'orange' : 'red'
                                )}
                                style={{ width: `${Math.min(avance, 100)}%` }}
                              />
                            </div>
                          </div>
                        </td>
                      </tr>

                      {isExpanded && (
                        <tr>
                          <td colSpan={10} className="p-0 bg-[#020B18]/60">
                            <div className="p-5 space-y-4 animate-fade-in">
                              <div className="flex justify-between items-center border-b border-white/[0.06] pb-3">
                                <h4 className="text-[10px] font-extrabold uppercase tracking-widest text-[#94A3B8] flex items-center gap-2">
                                  <span className="h-2 w-2 rounded-full bg-[#D40000]" />
                                  Distribución Mensual — Rubro {row.rubro} / {row.clasificador}
                                </h4>
                                <span className="text-[9px] text-[#4A6080] font-semibold">
                                  {row.clasificador_nombre}
                                </span>
                              </div>

                              {/* Monthly table */}
                              <div className="overflow-x-auto rounded-xl border border-white/[0.06] bg-[#03101F]/60">
                                <table className="w-full min-w-[780px] border-collapse text-[10px]">
                                  <thead>
                                    <tr className="border-b border-white/[0.06]">
                                      <th className="py-2.5 px-3 text-left font-bold text-[#4A6080] uppercase tracking-wider w-24">Concepto</th>
                                      {MONTHS.map((m) => (
                                        <th key={m} className="py-2.5 px-2 text-right font-bold text-[#4A6080]">{m}</th>
                                      ))}
                                      <th className="py-2.5 px-3 text-right font-bold text-[#94A3B8]">Total</th>
                                    </tr>
                                  </thead>
                                  <tbody className="font-mono">
                                    <tr className="border-b border-white/[0.04] hover:bg-white/[0.02]">
                                      <td className="py-2.5 px-3 font-sans font-bold text-red-400">Devengado</td>
                                      {([1,2,3,4,5,6,7,8,9,10,11,12] as const).map((m) => (
                                        <td key={m} className="py-2.5 px-2 text-right text-[#4A6080]">
                                          {formatMoney(row[`dev_${String(m).padStart(2,'0')}` as keyof GastoRow] as number)}
                                        </td>
                                      ))}
                                      <td className="py-2.5 px-3 text-right font-bold text-red-400 bg-red-950/10">
                                        {formatMoney(row.devengado_total)}
                                      </td>
                                    </tr>
                                    <tr className="hover:bg-white/[0.02]">
                                      <td className="py-2.5 px-3 font-sans font-bold text-emerald-400">Girado</td>
                                      {([1,2,3,4,5,6,7,8,9,10,11,12] as const).map((m) => (
                                        <td key={m} className="py-2.5 px-2 text-right text-[#4A6080]">
                                          {formatMoney(row[`gir_${String(m).padStart(2,'0')}` as keyof GastoRow] as number)}
                                        </td>
                                      ))}
                                      <td className="py-2.5 px-3 text-right font-bold text-emerald-400 bg-emerald-950/10">
                                        {formatMoney(row.girado_total)}
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                              </div>

                              {/* Detail cards */}
                              <div className="grid grid-cols-2 gap-3">
                                <div className="p-3 rounded-xl border border-white/[0.06] bg-white/[0.02] flex justify-between items-center">
                                  <div>
                                    <p className="text-[9px] uppercase tracking-widest font-bold text-[#4A6080]">Saldo por Devengar</p>
                                    <p className="font-mono font-bold text-[#D40000] mt-0.5">
                                      {formatMoney(row.pim - row.devengado_total)}
                                    </p>
                                  </div>
                                  <span className="text-[9px] text-[#4A6080] font-semibold">PIM − Devengado</span>
                                </div>
                                <div className="p-3 rounded-xl border border-white/[0.06] bg-white/[0.02] flex justify-between items-center">
                                  <div>
                                    <p className="text-[9px] uppercase tracking-widest font-bold text-[#4A6080]">Saldo por Comprometer</p>
                                    <p className="font-mono font-bold text-white mt-0.5">
                                      {formatMoney(row.pim - row.certificado)}
                                    </p>
                                  </div>
                                  <span className="text-[9px] text-[#4A6080] font-semibold">PIM − Certif.</span>
                                </div>
                              </div>
                            </div>
                          </td>
                        </tr>
                      )}
                    </Fragment>
                  );
                })
              )}
            </tbody>

            {/* Totals row */}
            {!loading && filteredRows.length > 0 && (
              <tfoot>
                <tr>
                  <td colSpan={4} className="font-sans font-extrabold uppercase tracking-wide text-[#94A3B8] text-[10px]">
                    Total Consolidado ({totalRecords} registros)
                  </td>
                  <td className="text-right font-mono">{formatMoney(totals.pia)}</td>
                  <td className="text-right font-mono text-white">{formatMoney(totals.pim)}</td>
                  <td className="text-right font-mono text-purple-400">{formatMoney(totals.certificado)}</td>
                  <td className="text-right font-mono text-red-400">{formatMoney(totals.devengado_total)}</td>
                  <td className="text-right font-mono text-emerald-400">{formatMoney(totals.girado_total)}</td>
                  <td className="text-center font-mono font-bold text-white">
                    {totals.pim > 0 ? ((totals.devengado_total / totals.pim) * 100).toFixed(1) : 0}%
                  </td>
                </tr>
              </tfoot>
            )}
          </table>
        </div>

        {/* Pagination */}
        {!loading && filteredRows.length > 0 && (
          <div className="px-5 py-4 border-t border-white/[0.05] bg-white/[0.02] flex flex-col sm:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-4 text-[11px] font-semibold text-[#4A6080]">
              <span className="flex items-center gap-2">
                Filas por página:
                <select
                  value={pageSize}
                  onChange={(e) => { setPageSize(Number(e.target.value)); setCurrentPage(1); }}
                  className="form-select w-auto !py-1 !px-2 !rounded-md"
                >
                  {[10,25,50,100].map(n => <option key={n} value={n}>{n}</option>)}
                </select>
              </span>
              <span>
                {startIndex + 1}–{Math.min(startIndex + pageSize, totalRecords)} de {totalRecords}
              </span>
            </div>

            <div className="flex items-center gap-1">
              {[
                { label: <ChevronLeft className="h-4 w-4" />, action: () => setCurrentPage(1), disabled: currentPage === 1 },
                { label: <><ChevronLeft className="h-3.5 w-3.5" />Ant.</>, action: () => setCurrentPage(p => Math.max(p-1,1)), disabled: currentPage === 1 },
              ].map((btn, i) => (
                <button key={i} onClick={btn.action} disabled={btn.disabled}
                  className="btn-secondary !px-2 !py-1.5 disabled:opacity-30 disabled:cursor-not-allowed flex items-center gap-0.5 text-[11px]">
                  {btn.label}
                </button>
              ))}

              {Array.from({ length: Math.min(5, totalPages) }).map((_, i) => {
                let p = i + 1;
                if (currentPage > 3 && totalPages > 5) {
                  p = currentPage - 3 + i;
                  if (p + (4 - i) > totalPages) p = totalPages - 4 + i;
                }
                return (
                  <button key={p} onClick={() => setCurrentPage(p)}
                    className={cn(
                      'w-8 h-8 rounded-lg text-[11px] font-bold border transition-all',
                      currentPage === p
                        ? 'bg-[#D40000] border-[#D40000] text-white shadow-lg shadow-red-950/50'
                        : 'btn-secondary !p-0'
                    )}>
                    {p}
                  </button>
                );
              })}

              {[
                { label: <>Sig.<ChevronRight className="h-3.5 w-3.5" /></>, action: () => setCurrentPage(p => Math.min(p+1,totalPages)), disabled: currentPage === totalPages },
                { label: <ChevronRight className="h-4 w-4" />, action: () => setCurrentPage(totalPages), disabled: currentPage === totalPages },
              ].map((btn, i) => (
                <button key={i} onClick={btn.action} disabled={btn.disabled}
                  className="btn-secondary !px-2 !py-1.5 disabled:opacity-30 disabled:cursor-not-allowed flex items-center gap-0.5 text-[11px]">
                  {btn.label}
                </button>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
