// src/app/pagos/page.tsx
'use client';

import { useState, useEffect, useCallback, Fragment } from 'react';
import { 
  CreditCard, 
  Search, 
  FileSpreadsheet, 
  ChevronDown, 
  ChevronUp, 
  RefreshCw, 
  SlidersHorizontal,
  Layers,
  ChevronLeft,
  ChevronRight,
  AlertTriangle,
  User,
  DollarSign,
  FileText,
  CheckCircle2,
  AlertCircle,
  HelpCircle
} from 'lucide-react';
import { cn } from '@/lib/utils';
import * as XLSX from 'xlsx';

interface PagoRow {
  id: number;
  ano_proc: string;
  ano_eje: string;
  sec_ejec: string;
  expediente: string;
  secuencia: string;
  num_doc: string;
  ruc: string;
  beneficiario: string;
  rubro: string;
  rubro_nombre: string;
  glosa: string;
  cod_doc: string;
  fecha_doc: string;
  cod_doc_b: string;
  nom_doc_b: string;
  fec_doc_b: string;
  const_pago: string;
  confor_doc: string;
  confor_des: string;
  confor_fec: string;
  monto: number;
  estado: string;
}

interface RubroOption {
  codigo: string;
  nombre: string;
}

export default function PagosPage() {
  const [loading, setLoading] = useState(true);
  const [rows, setRows] = useState<PagoRow[]>([]);
  const [rubrosList, setRubrosList] = useState<RubroOption[]>([]);
  
  // Filters
  const [filterRubro, setFilterRubro] = useState('');
  const [filterExpediente, setFilterExpediente] = useState('');
  const [filterEstado, setFilterEstado] = useState('');
  const [searchQuery, setSearchQuery] = useState('');

  // Expanded rows state
  const [expandedRows, setExpandedRows] = useState<Record<number, boolean>>({});

  // Pagination state
  const [currentPage, setCurrentPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);

  const fetchPagos = useCallback(async () => {
    setLoading(true);
    try {
      let url = '/api/pagos';
      const params = new URLSearchParams();
      if (filterRubro) params.append('rubro', filterRubro);
      if (filterExpediente) params.append('expediente', filterExpediente);
      if (filterEstado) params.append('estado', filterEstado);
      if (searchQuery) params.append('q', searchQuery);
      
      if (params.toString()) {
        url += `?${params.toString()}`;
      }

      const res = await fetch(url);
      const data = await res.json();
      if (data.success) {
        setRows(data.rows || []);
        if (data.rubros && rubrosList.length === 0) {
          setRubrosList(data.rubros);
        }
      }
    } catch (error) {
      console.error('Error fetching pagos data:', error);
    } finally {
      setLoading(false);
    }
  }, [filterRubro, filterExpediente, filterEstado, searchQuery, rubrosList.length]);

  useEffect(() => {
    fetchPagos();
    setCurrentPage(1); // Reset page on filter changes
  }, [fetchPagos]);

  // Format money to PEN currency style: S/ 1,234.56
  const formatMoney = (val: number) => {
    return new Intl.NumberFormat('es-PE', {
      style: 'currency',
      currency: 'PEN',
      minimumFractionDigits: 2,
    }).format(val || 0);
  };

  // Calculate totals of filtered rows (since backend returns already filtered rows, we use rows directly)
  const totalMonto = rows.reduce((acc, row) => acc + (row.monto || 0), 0);

  // Pagination logic
  const totalRecords = rows.length;
  const totalPages = Math.ceil(totalRecords / pageSize) || 1;
  const startIndex = (currentPage - 1) * pageSize;
  const paginatedRows = rows.slice(startIndex, startIndex + pageSize);

  const toggleRow = (rowId: number) => {
    setExpandedRows(prev => ({
      ...prev,
      [rowId]: !prev[rowId]
    }));
  };

  const toggleAllRows = () => {
    const allExpanded = Object.keys(expandedRows).length === paginatedRows.length && 
                        paginatedRows.every(r => expandedRows[r.id]);
    
    if (allExpanded) {
      setExpandedRows({});
    } else {
      const newExpanded: Record<number, boolean> = {};
      paginatedRows.forEach(r => {
        newExpanded[r.id] = true;
      });
      setExpandedRows(newExpanded);
    }
  };

  // Export to Excel function using xlsx
  const exportToExcel = () => {
    const exportData = rows.map((row) => ({
      'Expediente': row.expediente,
      'Secuencia': row.secuencia,
      'Num Doc': row.num_doc,
      'RUC': row.ruc,
      'Beneficiario': row.beneficiario,
      'Rubro': row.rubro,
      'Nombre Rubro': row.rubro_nombre || '',
      'Monto (S/)': row.monto,
      'Estado': row.estado || '',
      'Fecha Doc': row.fecha_doc || '',
      'Glosa': row.glosa || '',
      'Constancia Pago': row.const_pago || '',
      'Doc Banco': row.nom_doc_b || '',
      'Fec Banco': row.fec_doc_b || '',
      'Conformidad Doc': row.confor_doc || '',
      'Conformidad Des': row.confor_des || '',
      'Conformidad Fec': row.confor_fec || '',
    }));

    const worksheet = XLSX.utils.json_to_sheet(exportData);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Notas de Pago');
    
    // Auto-fit column widths
    const maxLens = Object.keys(exportData[0] || {}).map(key => {
      let maxLen = key.length;
      exportData.forEach(row => {
        const val = row[key as keyof typeof row];
        if (val !== null && val !== undefined) {
          maxLen = Math.max(maxLen, String(val).length);
        }
      });
      return { wch: Math.min(maxLen + 2, 50) }; // Cap width at 50 for very long texts like Glosa
    });
    worksheet['!cols'] = maxLens;

    XLSX.writeFile(workbook, `SWSiconis_Notas_Pago_${new Date().getFullYear()}.xlsx`);
  };

  // Status Badge Builder
  const getStatusBadge = (estado: string) => {
    const est = (estado || '').toLowerCase().trim();
    if (est === 'aprobado' || est === 'pagado') {
      return (
        <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-[10px] font-bold uppercase tracking-wider bg-emerald-950/40 border border-emerald-800/40 text-emerald-400">
          <CheckCircle2 className="h-3 w-3" />
          {estado}
        </span>
      );
    }
    if (est === 'proceso' || est === 'pendiente') {
      return (
        <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-[10px] font-bold uppercase tracking-wider bg-amber-950/40 border border-amber-800/40 text-amber-400">
          <AlertCircle className="h-3 w-3 animate-pulse" />
          {estado}
        </span>
      );
    }
    return (
      <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-[10px] font-bold uppercase tracking-wider bg-slate-900 border border-slate-700 text-slate-400">
        <HelpCircle className="h-3 w-3" />
        {estado || 'Sin Estado'}
      </span>
    );
  };

  return (
    <div className="space-y-8 animate-in fade-in duration-500">
      
      {/* Header Area */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-800/60 pb-6">
        <div>
          <div className="flex items-center gap-2 text-[#d40000] text-xs font-bold uppercase tracking-widest mb-1">
            <CreditCard className="h-4 w-4" />
            Módulo de Tesorería
          </div>
          <h1 className="text-2xl md:text-3xl font-extrabold text-white tracking-tight leading-none">
            Notas de Pago
          </h1>
          <p className="text-slate-400 text-xs mt-1 font-medium">
            Registro y seguimiento de expedientes, montos girados, beneficiarios y conformidades de pago.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <button 
            onClick={exportToExcel}
            disabled={loading || rows.length === 0}
            className="flex items-center gap-2 text-xs font-bold px-4 py-2.5 rounded-lg border border-emerald-800/60 bg-emerald-950/40 hover:bg-emerald-900/40 text-emerald-400 hover:text-emerald-300 transition-all duration-300 disabled:opacity-50 disabled:cursor-not-allowed shadow-md shadow-emerald-950/20"
          >
            <FileSpreadsheet className="h-4 w-4" />
            Exportar Excel
          </button>
          
          <button 
            onClick={fetchPagos}
            className="flex items-center justify-center p-2.5 rounded-lg border border-slate-800 bg-[#0b1329]/40 hover:bg-slate-800/40 text-slate-300 hover:text-white transition-all duration-300 backdrop-blur-sm"
            title="Actualizar datos"
          >
            <RefreshCw className={cn("h-4 w-4", loading && "animate-spin")} />
          </button>
        </div>
      </div>

      {/* Interactive Filters Panel */}
      <div className="p-5 rounded-2xl border border-slate-800/70 bg-[#091122]/40 backdrop-blur-md shadow-lg shadow-black/20 flex flex-col gap-4">
        <div className="flex items-center gap-2 text-xs font-bold text-slate-300 uppercase tracking-wider">
          <SlidersHorizontal className="h-4 w-4 text-[#d40000]" />
          Filtros y Búsqueda
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-4 gap-4">
          {/* Rubro Selector */}
          <div className="space-y-1.5">
            <label className="text-[10px] uppercase font-bold text-slate-500 tracking-wider flex items-center gap-1.5">
              <Layers className="h-3.5 w-3.5" />
              Rubro (Fuente Financ.)
            </label>
            <select
              value={filterRubro}
              onChange={(e) => setFilterRubro(e.target.value)}
              className="w-full text-xs bg-[#0b1428] border border-slate-800/80 rounded-xl px-3.5 py-2.5 text-slate-300 focus:outline-none focus:border-[#d40000]/60 transition-all duration-300"
            >
              <option value="">Todos los Rubros</option>
              {rubrosList.map((r) => (
                <option key={r.codigo} value={r.codigo}>
                  {r.codigo} - {r.nombre}
                </option>
              ))}
            </select>
          </div>

          {/* Expediente Filter */}
          <div className="space-y-1.5">
            <label className="text-[10px] uppercase font-bold text-slate-500 tracking-wider flex items-center gap-1.5">
              <FileText className="h-3.5 w-3.5" />
              Nro. Expediente SIAF
            </label>
            <input
              type="text"
              placeholder="Ej: 0000001..."
              value={filterExpediente}
              onChange={(e) => setFilterExpediente(e.target.value)}
              className="w-full text-xs bg-[#0b1428] border border-slate-800/80 rounded-xl px-3.5 py-2.5 text-slate-300 placeholder-slate-600 focus:outline-none focus:border-[#d40000]/60 transition-all duration-300"
            />
          </div>

          {/* Estado Selector */}
          <div className="space-y-1.5">
            <label className="text-[10px] uppercase font-bold text-slate-500 tracking-wider flex items-center gap-1.5">
              <CheckCircle2 className="h-3.5 w-3.5" />
              Estado de Pago
            </label>
            <select
              value={filterEstado}
              onChange={(e) => setFilterEstado(e.target.value)}
              className="w-full text-xs bg-[#0b1428] border border-slate-800/80 rounded-xl px-3.5 py-2.5 text-slate-300 focus:outline-none focus:border-[#d40000]/60 transition-all duration-300"
            >
              <option value="">Todos los Estados</option>
              <option value="Aprobado">Aprobado</option>
              <option value="Proceso">Proceso</option>
              <option value="Pendiente">Pendiente</option>
            </select>
          </div>

          {/* General Search Query */}
          <div className="space-y-1.5">
            <label className="text-[10px] uppercase font-bold text-slate-500 tracking-wider flex items-center gap-1.5">
              <Search className="h-3.5 w-3.5" />
              Buscar Beneficiario / RUC / Doc
            </label>
            <input
              type="text"
              placeholder="Ej: Consorcio o RUC..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full text-xs bg-[#0b1428] border border-slate-800/80 rounded-xl px-3.5 py-2.5 text-slate-300 placeholder-slate-600 focus:outline-none focus:border-[#d40000]/60 transition-all duration-300"
            />
          </div>
        </div>
      </div>

      {/* Summary KPI Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="p-5 rounded-2xl border border-slate-800/50 bg-[#091224]/30 backdrop-blur-md relative overflow-hidden group">
          <div className="absolute top-0 right-0 p-4 opacity-5 group-hover:opacity-10 transition-opacity">
            <DollarSign className="h-14 w-14 text-white" />
          </div>
          <p className="text-[9px] uppercase font-bold text-slate-400 tracking-widest mb-1.5">Monto Total Girado</p>
          <h3 className="text-xl font-extrabold text-white">{formatMoney(totalMonto)}</h3>
          <div className="mt-2 text-[10px] text-slate-500 font-semibold">
            Suma total de notas de pago filtradas
          </div>
          <div className="absolute left-0 bottom-0 top-0 w-1 bg-[#d40000]" />
        </div>

        <div className="p-5 rounded-2xl border border-slate-800/50 bg-[#091224]/30 backdrop-blur-md relative overflow-hidden group">
          <div className="absolute top-0 right-0 p-4 opacity-5 group-hover:opacity-10 transition-opacity">
            <FileText className="h-14 w-14 text-white" />
          </div>
          <p className="text-[9px] uppercase font-bold text-slate-400 tracking-widest mb-1.5">Expedientes Totales</p>
          <h3 className="text-xl font-extrabold text-white">{totalRecords}</h3>
          <div className="mt-2 text-[10px] text-slate-500 font-semibold">
            Cantidad de registros encontrados
          </div>
          <div className="absolute left-0 bottom-0 top-0 w-1 bg-slate-700" />
        </div>

        <div className="p-5 rounded-2xl border border-slate-800/50 bg-[#091224]/30 backdrop-blur-md relative overflow-hidden group">
          <div className="absolute top-0 right-0 p-4 opacity-5 group-hover:opacity-10 transition-opacity">
            <CheckCircle2 className="h-14 w-14 text-white" />
          </div>
          <p className="text-[9px] uppercase font-bold text-slate-400 tracking-widest mb-1.5">Eficiencia de Pago</p>
          <h3 className="text-xl font-extrabold text-emerald-400">
            {totalRecords > 0 
              ? ((rows.filter(r => (r.estado || '').toLowerCase() === 'aprobado').length / totalRecords) * 100).toFixed(1)
              : 0}%
          </h3>
          <div className="mt-2 text-[10px] text-slate-550 font-semibold text-emerald-500/80">
            Porcentaje de expedientes en estado Aprobado
          </div>
          <div className="absolute left-0 bottom-0 top-0 w-1 bg-emerald-600" />
        </div>
      </div>

      {/* Main Table Container */}
      <div className="rounded-2xl border border-slate-800/80 bg-[#081020]/60 backdrop-blur-md shadow-2xl overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="border-b border-slate-800 bg-slate-900/35 text-slate-400 text-[10px] uppercase font-bold tracking-wider">
                <th className="py-4 px-5 w-12 text-center">
                  <button 
                    onClick={toggleAllRows}
                    className="p-1 rounded bg-slate-800/60 hover:bg-slate-700/60 transition-colors"
                    title="Expandir/Contraer todos"
                  >
                    <ChevronDown className="h-3.5 w-3.5 text-slate-300" />
                  </button>
                </th>
                <th className="py-4 px-4 w-28">Expediente</th>
                <th className="py-4 px-4 w-20 text-center">Sec.</th>
                <th className="py-4 px-4 w-28 text-center">Rubro</th>
                <th className="py-4 px-4">Beneficiario / RUC</th>
                <th className="py-4 px-4">Documento</th>
                <th className="py-4 px-4 text-right">Monto</th>
                <th className="py-4 px-4 text-center w-36">Estado</th>
              </tr>
            </thead>
            
            <tbody className="divide-y divide-slate-800/40 text-xs font-medium text-slate-300">
              {loading ? (
                // Skeleton Rows
                Array.from({ length: 5 }).map((_, idx) => (
                  <tr key={idx} className="animate-pulse">
                    <td className="py-5 px-5"><div className="h-4 w-4 bg-slate-800 rounded mx-auto" /></td>
                    <td className="py-5 px-4"><div className="h-4 w-16 bg-slate-800 rounded" /></td>
                    <td className="py-5 px-4"><div className="h-4 w-8 bg-slate-800 rounded mx-auto" /></td>
                    <td className="py-5 px-4"><div className="h-4 w-10 bg-slate-800 rounded mx-auto" /></td>
                    <td className="py-5 px-4"><div className="h-4 w-48 bg-slate-800 rounded" /></td>
                    <td className="py-5 px-4"><div className="h-4 w-28 bg-slate-800 rounded" /></td>
                    <td className="py-5 px-4"><div className="h-4 w-16 bg-slate-800 rounded ml-auto" /></td>
                    <td className="py-5 px-4"><div className="h-6 w-20 bg-slate-800 rounded-full mx-auto" /></td>
                  </tr>
                ))
              ) : paginatedRows.length === 0 ? (
                <tr>
                  <td colSpan={8} className="py-12 text-center text-slate-500 font-semibold">
                    <div className="flex flex-col items-center justify-center gap-2">
                      <AlertTriangle className="h-8 w-8 text-slate-600" />
                      <span>No se encontraron registros de notas de pago.</span>
                    </div>
                  </td>
                </tr>
              ) : (
                paginatedRows.map((row) => {
                  const isExpanded = !!expandedRows[row.id];
                  
                  return (
                    <Fragment key={row.id}>
                      {/* Base Row */}
                      <tr 
                        className={cn(
                          "hover:bg-[#0c162b]/40 transition-colors duration-200 cursor-pointer",
                          isExpanded && "bg-[#0b152d]/60 border-l-2 border-[#d40000]"
                        )}
                        onClick={() => toggleRow(row.id)}
                      >
                        <td className="py-4 px-5 text-center">
                          <button className="p-1 rounded hover:bg-slate-800/80 transition-colors">
                            {isExpanded ? (
                              <ChevronUp className="h-4 w-4 text-[#d40000]" />
                            ) : (
                              <ChevronDown className="h-4 w-4 text-slate-400" />
                            )}
                          </button>
                        </td>
                        <td className="py-4 px-4 font-mono font-bold text-white tracking-wide">{row.expediente}</td>
                        <td className="py-4 px-4 text-center font-semibold text-slate-400">{row.secuencia}</td>
                        <td className="py-4 px-4 text-center font-bold text-slate-400" title={row.rubro_nombre}>{row.rubro}</td>
                        <td className="py-4 px-4 max-w-[250px] truncate">
                          <p className="font-semibold text-slate-200 truncate flex items-center gap-1.5">
                            <User className="h-3 w-3 text-slate-500 shrink-0" />
                            {row.beneficiario || 'Sin beneficiario'}
                          </p>
                          <p className="text-[10px] text-slate-500 font-semibold pl-4">RUC: {row.ruc || 'N/A'}</p>
                        </td>
                        <td className="py-4 px-4 max-w-[200px] truncate" title={row.num_doc}>
                          <p className="font-semibold text-slate-300 truncate">{row.num_doc || 'Sin documento'}</p>
                          <p className="text-[10px] text-slate-550">{row.fecha_doc || 'Sin fecha'}</p>
                        </td>
                        <td className="py-4 px-4 text-right font-mono font-bold text-white">{formatMoney(row.monto)}</td>
                        <td className="py-4 px-4 text-center">{getStatusBadge(row.estado)}</td>
                      </tr>

                      {/* Expandable Details Row */}
                      {isExpanded && (
                        <tr>
                          <td colSpan={8} className="p-0 bg-slate-950/45 border-b border-slate-800/40">
                            <div className="p-6 space-y-5 animate-in slide-in-from-top-2 duration-300">
                              {/* Glosa block */}
                              <div className="space-y-1.5">
                                <span className="text-[9px] uppercase font-bold text-slate-500 tracking-wider block">Glosa del Expediente / Detalle del Pago</span>
                                <div className="p-4 rounded-xl border border-slate-800 bg-[#091122]/70 text-slate-300 leading-relaxed font-sans text-xs shadow-inner">
                                  {row.glosa || 'No se ha registrado glosa para esta nota de pago.'}
                                </div>
                              </div>

                              {/* Details Grid */}
                              <div className="grid grid-cols-1 md:grid-cols-3 gap-6 pt-1">
                                {/* Doc details */}
                                <div className="space-y-2">
                                  <h4 className="text-[10px] uppercase font-bold text-slate-400 border-b border-slate-850 pb-1 flex items-center gap-1.5">
                                    <FileText className="h-3.5 w-3.5 text-slate-500" />
                                    Información del Documento
                                  </h4>
                                  <div className="space-y-1.5 text-xs">
                                    <p className="text-slate-500 font-semibold">Código Doc: <span className="text-slate-300 font-mono font-bold">{row.cod_doc || 'N/A'}</span></p>
                                    <p className="text-slate-500 font-semibold">Fecha Emisión: <span className="text-slate-300">{row.fecha_doc || 'N/A'}</span></p>
                                    <p className="text-slate-500 font-semibold">Constancia Pago: <span className="text-slate-300 font-mono">{row.const_pago || 'N/A'}</span></p>
                                  </div>
                                </div>

                                {/* Bank details */}
                                <div className="space-y-2">
                                  <h4 className="text-[10px] uppercase font-bold text-slate-400 border-b border-slate-850 pb-1 flex items-center gap-1.5">
                                    <CreditCard className="h-3.5 w-3.5 text-slate-500" />
                                    Detalle de Banco / Cheque
                                  </h4>
                                  <div className="space-y-1.5 text-xs">
                                    <p className="text-slate-500 font-semibold">Código Banco: <span className="text-slate-300 font-mono">{row.cod_doc_b || 'N/A'}</span></p>
                                    <p className="text-slate-500 font-semibold">Documento Banco: <span className="text-slate-300" title={row.nom_doc_b}>{row.nom_doc_b || 'N/A'}</span></p>
                                    <p className="text-slate-500 font-semibold">Fecha Banco: <span className="text-slate-300">{row.fec_doc_b || 'N/A'}</span></p>
                                  </div>
                                </div>

                                {/* Conformity details */}
                                <div className="space-y-2">
                                  <h4 className="text-[10px] uppercase font-bold text-slate-400 border-b border-slate-850 pb-1 flex items-center gap-1.5">
                                    <CheckCircle2 className="h-3.5 w-3.5 text-slate-500" />
                                    Conformidad de Pago
                                  </h4>
                                  <div className="space-y-1.5 text-xs">
                                    <p className="text-slate-500 font-semibold">Doc Conformidad: <span className="text-slate-300" title={row.confor_doc}>{row.confor_doc || 'N/A'}</span></p>
                                    <p className="text-slate-500 font-semibold">Destinatario: <span className="text-slate-300" title={row.confor_des}>{row.confor_des || 'N/A'}</span></p>
                                    <p className="text-slate-500 font-semibold">Fecha Conformidad: <span className="text-slate-300">{row.confor_fec || 'N/A'}</span></p>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </td>
                        </tr>
                      )}
                    </Fragment>
                  );
                })
              )}
            </tbody>
          </table>
        </div>

        {/* Client Side Pagination Controls */}
        {!loading && rows.length > 0 && (
          <div className="px-5 py-4 border-t border-slate-800/80 bg-slate-900/20 flex flex-col sm:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-4 text-xs font-semibold text-slate-400">
              <span className="flex items-center gap-2">
                Filas por página:
                <select
                  value={pageSize}
                  onChange={(e) => {
                    setPageSize(Number(e.target.value));
                    setCurrentPage(1);
                  }}
                  className="bg-[#0b1428] border border-slate-800 rounded px-2.5 py-1 text-slate-300 focus:outline-none focus:border-[#d40000]/60 transition-colors"
                >
                  <option value={10}>10</option>
                  <option value={25}>25</option>
                  <option value={50}>50</option>
                  <option value={100}>100</option>
                </select>
              </span>
              <span>
                Mostrando {startIndex + 1} a {Math.min(startIndex + pageSize, totalRecords)} de {totalRecords} registros
              </span>
            </div>

            <div className="flex items-center gap-1.5">
              <button
                onClick={() => setCurrentPage(1)}
                disabled={currentPage === 1}
                className="p-2 rounded-lg border border-slate-800 bg-[#0b1329]/40 hover:bg-slate-800/40 text-slate-400 hover:text-white transition-all disabled:opacity-30 disabled:cursor-not-allowed"
                title="Primera página"
              >
                <ChevronLeft className="h-4 w-4 transform -translate-x-0.5" />
              </button>
              <button
                onClick={() => setCurrentPage(prev => Math.max(prev - 1, 1))}
                disabled={currentPage === 1}
                className="flex items-center gap-1 px-3 py-1.5 rounded-lg border border-slate-800 bg-[#0b1329]/40 hover:bg-slate-800/40 text-slate-400 hover:text-white transition-all disabled:opacity-30 disabled:cursor-not-allowed text-xs font-bold"
              >
                <ChevronLeft className="h-3.5 w-3.5" />
                Anterior
              </button>
              
              <div className="flex items-center gap-1">
                {Array.from({ length: Math.min(5, totalPages) }).map((_, i) => {
                  let pageNum = i + 1;
                  if (currentPage > 3 && totalPages > 5) {
                    pageNum = currentPage - 3 + i;
                    if (pageNum + (4 - i) > totalPages) {
                      pageNum = totalPages - 4 + i;
                    }
                  }
                  
                  return (
                    <button
                      key={pageNum}
                      onClick={() => setCurrentPage(pageNum)}
                      className={cn(
                        "w-8 h-8 rounded-lg text-xs font-bold border transition-all duration-200",
                        currentPage === pageNum 
                          ? "bg-[#d40000] border-[#d40000] text-white shadow-lg shadow-red-950/45" 
                          : "border-slate-800 bg-[#0b1329]/20 hover:bg-slate-800/50 text-slate-400 hover:text-white"
                      )}
                    >
                      {pageNum}
                    </button>
                  );
                })}
              </div>

              <button
                onClick={() => setCurrentPage(prev => Math.min(prev + 1, totalPages))}
                disabled={currentPage === totalPages}
                className="flex items-center gap-1 px-3 py-1.5 rounded-lg border border-slate-800 bg-[#0b1329]/40 hover:bg-slate-800/40 text-slate-400 hover:text-white transition-all disabled:opacity-30 disabled:cursor-not-allowed text-xs font-bold"
              >
                Siguiente
                <ChevronRight className="h-3.5 w-3.5" />
              </button>
              <button
                onClick={() => setCurrentPage(totalPages)}
                disabled={currentPage === totalPages}
                className="p-2 rounded-lg border border-slate-800 bg-[#0b1329]/40 hover:bg-[#0b1329]/40 text-slate-400 hover:text-white transition-all disabled:opacity-30 disabled:cursor-not-allowed"
                title="Última página"
              >
                <ChevronRight className="h-4 w-4 transform translate-x-0.5" />
              </button>
            </div>
          </div>
        )}
      </div>

    </div>
  );
}

// frontend/src/app/pages/pagos/pagos.component.ts
import { Component, OnInit, signal, computed, effect } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../services/api.service';
import { PagoRow, RubroOption } from '../../models/api.models';
import * as XLSX from 'xlsx';

@Component({
  selector: 'app-pagos',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './pagos.component.html',
  styleUrls: []
})
export class PagosComponent implements OnInit {
  loading = signal(true);
  rows = signal<PagoRow[]>([]);
  rubrosList = signal<RubroOption[]>([]);
  
  // Filters
  filterRubro = signal('');
  filterExpediente = signal('');
  filterEstado = signal('');
  searchQuery = signal('');

  // Expanded rows state (using record dictionary for row tracking: number ID)
  expandedRows = signal<Record<number, boolean>>({});

  // Pagination
  currentPage = signal(1);
  pageSize = signal(10);

  // Computeds
  // The API returns already filtered records for 'q' search, but we can compute totals and paginated rows.
  totalMonto = computed(() => {
    return this.rows().reduce((acc, row) => acc + (row.monto || 0), 0);
  });

  paginatedRows = computed(() => {
    const list = this.rows();
    const start = (this.currentPage() - 1) * this.pageSize();
    return list.slice(start, start + this.pageSize());
  });

  totalPages = computed(() => {
    const total = this.rows().length;
    return Math.ceil(total / this.pageSize()) || 1;
  });

  constructor(private apiService: ApiService) {
    // Fetch data when filter signals change
    effect(() => {
      this.fetchPagos();
      this.currentPage.set(1); // Reset page on filter changes
    }, { allowSignalWrites: true });
  }

  ngOnInit(): void {}

  fetchPagos(): void {
    this.loading.set(true);
    const filters = {
      rubro: this.filterRubro(),
      expediente: this.filterExpediente(),
      estado: this.filterEstado(),
      q: this.searchQuery()
    };

    this.apiService.getPagos(filters).subscribe({
      next: (data) => {
        if (data.success) {
          this.rows.set(data.rows || []);
          if (data.rubros && this.rubrosList().length === 0) {
            this.rubrosList.set(data.rubros);
          }
        }
        this.loading.set(false);
      },
      error: (error) => {
        console.error('Error fetching pagos:', error);
        this.loading.set(false);
      }
    });
  }

  toggleRow(id: number): void {
    const current = { ...this.expandedRows() };
    current[id] = !current[id];
    this.expandedRows.set(current);
  }

  isExpanded(id: number): boolean {
    return !!this.expandedRows()[id];
  }

  toggleAllRows(): void {
    const paginated = this.paginatedRows();
    const current = this.expandedRows();
    const allExpanded = paginated.every(r => current[r.id]);

    if (allExpanded) {
      const updated = { ...current };
      paginated.forEach(r => {
        delete updated[r.id];
      });
      this.expandedRows.set(updated);
    } else {
      const updated = { ...current };
      paginated.forEach(r => {
        updated[r.id] = true;
      });
      this.expandedRows.set(updated);
    }
  }

  formatMoney(val: number): string {
    return new Intl.NumberFormat('es-PE', {
      style: 'currency',
      currency: 'PEN',
      minimumFractionDigits: 2,
    }).format(val || 0);
  }

  // Get status details for UI classes
  getStatusType(estado: string): 'success' | 'warning' | 'default' {
    const est = (estado || '').toLowerCase().trim();
    if (est === 'aprobado' || est === 'pagado') {
      return 'success';
    }
    if (est === 'proceso' || est === 'pendiente') {
      return 'warning';
    }
    return 'default';
  }

  exportToExcel(): void {
    const exportData = this.rows().map((row) => ({
      'Expediente': row.expediente,
      'Secuencia': row.secuencia,
      'Num Doc': row.num_doc,
      'RUC': row.ruc,
      'Beneficiario': row.beneficiario,
      'Rubro': row.rubro,
      'Nombre Rubro': row.rubro_nombre || '',
      'Monto (S/)': row.monto,
      'Estado': row.estado || '',
      'Fecha Doc': row.fecha_doc || '',
      'Glosa': row.glosa || '',
      'Constancia Pago': row.const_pago || '',
      'Doc Banco': row.nom_doc_b || '',
      'Fec Banco': row.fec_doc_b || '',
      'Conformidad Doc': row.confor_doc || '',
      'Conformidad Des': row.confor_des || '',
      'Conformidad Fec': row.confor_fec || '',
    }));

    const worksheet = XLSX.utils.json_to_sheet(exportData);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, 'Notas de Pago');
    
    // Auto-fit column widths
    const maxLens = Object.keys(exportData[0] || {}).map(key => {
      let maxLen = key.length;
      exportData.forEach(row => {
        const val = row[key as keyof typeof row];
        if (val !== null && val !== undefined) {
          maxLen = Math.max(maxLen, String(val).length);
        }
      });
      return { wch: Math.min(maxLen + 2, 50) }; // Cap width at 50
    });
    worksheet['!cols'] = maxLens;

    XLSX.writeFile(workbook, `SWSiconis_Notas_Pago_${new Date().getFullYear()}.xlsx`);
  }

  changePage(dir: number): void {
    const next = this.currentPage() + dir;
    if (next >= 1 && next <= this.totalPages()) {
      this.currentPage.set(next);
    }
  }
}

<div class="space-y-8 animate-in">
  
  <!-- Header Area -->
  <div class="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-800/60 pb-6">
    <div>
      <div class="flex items-center gap-2 text-[#d40000] text-xs font-bold uppercase tracking-widest mb-1">
        <!-- Credit Card Icon SVG -->
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="h-4 w-4">
          <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 8.25h19.5M2.25 9h19.5m-19.5 8.25h2.25m3 0h2.25m-9-1.125h1.5a1.125 1.125 0 001.125-1.125V9.75M8.25 19.5a.75.75 0 010-1.5h-.75a.75.75 0 00-.75-.75h-.75a.75.75 0 00-.75.75v.75m3 0V18a1.5 1.5 0 00-1.5-1.5H5.25A1.5 1.5 0 003.75 18v1.5m10.5-11.25h.008v.008h-.008V8.25zm.375 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z" />
        </svg>
        Módulo de Tesorería
      </div>
      <h1 class="text-2xl md:text-3xl font-extrabold text-white tracking-tight leading-none">
        Notas de Pago
      </h1>
      <p class="text-slate-400 text-xs mt-1 font-medium">
        Registro y seguimiento de expedientes, montos girados, beneficiarios y conformidades de pago.
      </p>
    </div>

    <div class="flex items-center gap-3">
      <button 
        (click)="exportToExcel()"
        [disabled]="loading() || rows().length === 0"
        class="flex items-center gap-2 text-xs font-bold px-4 py-2.5 rounded-lg border border-emerald-800/60 bg-emerald-950/40 hover:bg-emerald-900/40 text-emerald-400 hover:text-emerald-300 transition-all duration-300 disabled:opacity-50 disabled:cursor-not-allowed shadow-md shadow-emerald-950/20"
      >
        <!-- FileSpreadsheet Icon SVG -->
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="h-4 w-4">
          <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m6.75 12H9m1.5-12H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" />
        </svg>
        Exportar Excel
      </button>
      
      <button 
        (click)="fetchPagos()"
        class="flex items-center justify-center p-2.5 rounded-lg border border-slate-800 bg-[#0b1329]/40 hover:bg-slate-800/40 text-slate-300 hover:text-white transition-all duration-300 backdrop-blur-sm"
        title="Actualizar datos"
      >
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2.5" stroke="currentColor" class="h-4 w-4" [ngClass]="{'animate-spin': loading()}">
          <path stroke-linecap="round" stroke-linejoin="round" d="M16.023 9.348h4.992v-.001M2.985 19.644v-4.992m0 0h4.992m-4.993 0l3.181 3.183a8.25 8.25 0 0013.803-3.7M4.031 9.865a8.25 8.25 0 0113.803-3.7l3.181 3.182m0-4.991v4.99" />
        </svg>
      </button>
    </div>
  </div>

  <!-- Interactive Filters Panel -->
  <div class="p-5 rounded-2xl border border-slate-800/70 bg-[#091122]/40 backdrop-blur-md shadow-lg shadow-black/20 flex flex-col gap-4">
    <div class="flex items-center gap-2 text-xs font-bold text-slate-300 uppercase tracking-wider">
      <!-- Sliders Icon SVG -->
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="h-4 w-4 text-[#d40000]">
        <path stroke-linecap="round" stroke-linejoin="round" d="M10.5 6h9.75M10.5 6a1.5 1.5 0 11-3 0m3 0a1.5 1.5 0 10-3 0M3.75 6H7.5m3 12h9.75m-9.75 0a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m-3.75 0H7.5m9-6h3.75m-3.75 0a1.5 1.5 0 01-3 0m3 0a1.5 1.5 0 00-3 0m-9.75 0h9.75" />
      </svg>
      Filtros de Búsqueda
    </div>

    <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
      <!-- Rubro Selector -->
      <div class="space-y-1.5">
        <label class="text-[10px] uppercase font-bold text-slate-500 tracking-wider flex items-center gap-1.5">
          <!-- Layers Icon SVG -->
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="h-3.5 w-3.5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6.429 9.75L2.25 12l4.179 2.25m11.142 0L21.75 12l-4.179-2.25m-11.142 0L10.5 7.5 12 6.75l1.5.75 4.179 2.25m-11.142 0L12 12l5.571-2.25M6.429 14.25L12 16.5l5.571-2.25M12 16.5v4.5m-3.75-2.25h7.5" />
          </svg>
          Rubro
        </label>
        <select
          [ngModel]="filterRubro()"
          (ngModelChange)="filterRubro.set($event)"
          class="w-full text-xs bg-[#0b1428] border border-slate-800/80 rounded-xl px-3.5 py-2.5 text-slate-300 focus:outline-none focus:border-[#d40000]/60 transition-all duration-300"
        >
          <option value="">Todos los Rubros</option>
          @for (r of rubrosList(); track r.codigo) {
            <option [value]="r.codigo">{{ r.codigo }} - {{ r.nombre }}</option>
          }
        </select>
      </div>

      <!-- Expediente input -->
      <div class="space-y-1.5">
        <label class="text-[10px] uppercase font-bold text-slate-500 tracking-wider flex items-center gap-1.5">
          <!-- FileText Icon SVG -->
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="h-3.5 w-3.5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" />
          </svg>
          Nro. Expediente
        </label>
        <input
          type="text"
          placeholder="Ej: 000451..."
          [ngModel]="filterExpediente()"
          (ngModelChange)="filterExpediente.set($event)"
          class="w-full text-xs bg-[#0b1428] border border-slate-800/80 rounded-xl px-3.5 py-2.5 text-slate-300 placeholder-slate-600 focus:outline-none focus:border-[#d40000]/60 transition-all duration-300"
        />
      </div>

      <!-- Estado selector -->
      <div class="space-y-1.5">
        <label class="text-[10px] uppercase font-bold text-slate-500 tracking-wider flex items-center gap-1.5">
          <!-- CheckCircle2 Icon SVG -->
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="h-3.5 w-3.5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          Estado Pago
        </label>
        <select
          [ngModel]="filterEstado()"
          (ngModelChange)="filterEstado.set($event)"
          class="w-full text-xs bg-[#0b1428] border border-slate-800/80 rounded-xl px-3.5 py-2.5 text-slate-300 focus:outline-none focus:border-[#d40000]/60 transition-all duration-300"
        >
          <option value="">Todos los Estados</option>
          <option value="APROBADO">APROBADO</option>
          <option value="PAGADO">PAGADO</option>
          <option value="PROCESO">PROCESO</option>
          <option value="PENDIENTE">PENDIENTE</option>
        </select>
      </div>

      <!-- Global Text Search (Beneficiary, Ruc, Num Doc) -->
      <div class="space-y-1.5">
        <label class="text-[10px] uppercase font-bold text-slate-500 tracking-wider flex items-center gap-1.5">
          <!-- Search Icon SVG -->
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="h-3.5 w-3.5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
          </svg>
          Búsqueda de Beneficiario / RUC
        </label>
        <div class="relative">
          <input
            type="text"
            placeholder="Nombre, RUC o Nro Doc..."
            [ngModel]="searchQuery()"
            (ngModelChange)="searchQuery.set($event)"
            class="w-full text-xs bg-[#0b1428] border border-slate-800/80 rounded-xl pl-9 pr-3.5 py-2.5 text-slate-300 placeholder-slate-600 focus:outline-none focus:border-[#d40000]/60 transition-all duration-300"
          />
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="absolute left-3.5 top-3.5 h-3.5 w-3.5 text-slate-600">
            <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
          </svg>
        </div>
      </div>
    </div>
  </div>

  <!-- Summary Mini Cards -->
  <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
    <div class="p-4 rounded-xl border border-slate-800/50 bg-[#091224]/20 backdrop-blur-md">
      <p class="text-[9px] uppercase font-bold text-slate-500 tracking-widest mb-1">Total Monto Desembolsado</p>
      <p class="text-xl font-black text-white">{{ formatMoney(totalMonto()) }}</p>
    </div>
    <div class="p-4 rounded-xl border border-slate-800/50 bg-[#091224]/20 backdrop-blur-md">
      <p class="text-[9px] uppercase font-bold text-slate-500 tracking-widest mb-1">Registros Encontrados</p>
      <p class="text-xl font-black text-slate-300">{{ rows().length }} notas de pago</p>
    </div>
  </div>

  <!-- Main Table Container -->
  <div class="rounded-2xl border border-slate-800/80 bg-[#081020]/60 backdrop-blur-md shadow-2xl overflow-hidden">
    <div class="overflow-x-auto">
      <table class="w-full text-left border-collapse">
        <thead>
          <tr class="border-b border-slate-800 bg-slate-900/35 text-slate-400 text-[10px] uppercase font-bold tracking-wider">
            <th class="py-4 px-5 w-12 text-center">
              <button 
                (click)="toggleAllRows()"
                class="p-1 rounded bg-slate-800/60 hover:bg-slate-700/60 transition-colors"
                title="Expandir/Contraer todos"
              >
                <!-- Chevron Down Icon -->
                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2.5" stroke="currentColor" class="h-3.5 w-3.5 text-slate-300">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
                </svg>
              </button>
            </th>
            <th class="py-4 px-4 w-28 text-center">Expediente</th>
            <th class="py-4 px-2 w-14 text-center">Sec.</th>
            <th class="py-4 px-4 w-32">RUC</th>
            <th class="py-4 px-4">Beneficiario</th>
            <th class="py-4 px-4 w-16 text-center">Rubro</th>
            <th class="py-4 px-4 w-44">Documento</th>
            <th class="py-4 px-4 w-28 text-center">Fecha Doc</th>
            <th class="py-4 px-4 text-right">Monto</th>
            <th class="py-4 px-4 text-center w-28">Estado</th>
          </tr>
        </thead>
        
        <tbody class="divide-y divide-slate-800/40 text-xs font-medium text-slate-300">
          @if (loading()) {
            @for (skele of [1,2,3,4,5]; track skele) {
              <tr class="animate-pulse">
                <td class="py-5 px-5"><div class="h-4 w-4 bg-slate-800 rounded mx-auto" /></td>
                <td class="py-5 px-4"><div class="h-4 w-16 bg-slate-800 rounded mx-auto" /></td>
                <td class="py-5 px-2"><div class="h-4 w-6 bg-slate-800 rounded mx-auto" /></td>
                <td class="py-5 px-4"><div class="h-4 w-20 bg-slate-800 rounded" /></td>
                <td class="py-5 px-4"><div class="h-4 w-36 bg-slate-800 rounded" /></td>
                <td class="py-5 px-4"><div class="h-4 w-6 bg-slate-800 rounded mx-auto" /></td>
                <td class="py-5 px-4"><div class="h-4 w-24 bg-slate-800 rounded" /></td>
                <td class="py-5 px-4"><div class="h-4 w-16 bg-slate-800 rounded mx-auto" /></td>
                <td class="py-5 px-4"><div class="h-4 w-16 bg-slate-800 rounded ml-auto" /></td>
                <td class="py-5 px-4"><div class="h-4 w-14 bg-slate-800 rounded mx-auto" /></td>
              </tr>
            }
          } @else {
            @for (row of paginatedRows(); track row.id) {
              <tr class="hover:bg-slate-900/40 transition-colors duration-200">
                <td class="py-4 px-5 text-center">
                  <button 
                    (click)="toggleRow(row.id)"
                    class="p-1 rounded bg-slate-950/60 hover:bg-slate-800 border border-slate-800 transition-colors"
                  >
                    @if (isExpanded(row.id)) {
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2.5" stroke="currentColor" class="h-3.5 w-3.5 text-[#d40000]">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 15.75l7.5-7.5 7.5 7.5" />
                      </svg>
                    } @else {
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2.5" stroke="currentColor" class="h-3.5 w-3.5 text-slate-400">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
                      </svg>
                    }
                  </button>
                </td>
                <td class="py-4 px-4 text-center font-mono font-bold text-slate-300">{{ row.expediente }}</td>
                <td class="py-4 px-2 text-center text-slate-500">{{ row.secuencia }}</td>
                <td class="py-4 px-4 font-mono text-slate-400">{{ row.ruc || 'N/A' }}</td>
                <td class="py-4 px-4 font-bold text-slate-100 truncate max-w-xs" [title]="row.beneficiario">{{ row.beneficiario }}</td>
                <td class="py-4 px-4 text-center font-mono text-slate-400 font-semibold">{{ row.rubro }}</td>
                <td class="py-4 px-4 font-semibold text-slate-300 truncate max-w-[12rem]">{{ row.num_doc }}</td>
                <td class="py-4 px-4 text-center text-slate-400">{{ row.fecha_doc }}</td>
                <td class="py-4 px-4 text-right text-white font-extrabold">{{ formatMoney(row.monto) }}</td>
                <td class="py-4 px-4 text-center">
                  @if (getStatusType(row.estado) === 'success') {
                    <span class="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-[10px] font-bold uppercase tracking-wider bg-emerald-950/40 border border-emerald-800/40 text-emerald-400">
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="3" stroke="currentColor" class="h-3 w-3">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M4.5 12.75l6 6 9-13.5" />
                      </svg>
                      {{ row.estado }}
                    </span>
                  } @else if (getStatusType(row.estado) === 'warning') {
                    <span class="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-[10px] font-bold uppercase tracking-wider bg-amber-950/40 border border-amber-800/40 text-amber-400">
                      <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="3" stroke="currentColor" class="h-3 w-3 animate-pulse">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v3.75m9-.75a9 9 0 11-18 0 9 9 0 0118 0zm-9 3.75h.008v.008H12v-.008z" />
                      </svg>
                      {{ row.estado }}
                    </span>
                  } @else {
                    <span class="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-[10px] font-bold uppercase tracking-wider bg-slate-900 border border-slate-700 text-slate-400">
                      {{ row.estado || 'Sin Estado' }}
                    </span>
                  }
                </td>
              </tr>

              <!-- Expanded Row Details for payment notes -->
              @if (isExpanded(row.id)) {
                <tr class="bg-[#050b16]/70 border-l-2 border-[#d40000]">
                  <td colspan="10" class="p-6">
                    <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
                      
                      <!-- Col 1: Payment Glosa description -->
                      <div class="md:col-span-2 space-y-2">
                        <div class="text-[10px] uppercase font-bold text-slate-500 tracking-wider flex items-center gap-1.5">
                          <!-- FileText SVG Icon -->
                          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="h-3.5 w-3.5">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z" />
                          </svg>
                          Descripción / Glosa del Expediente
                        </div>
                        <p class="text-xs text-slate-200 leading-relaxed font-semibold bg-slate-950/30 p-3.5 rounded-xl border border-slate-800/40">
                          {{ row.glosa || 'No se registra glosa descriptiva para esta nota de pago.' }}
                        </p>
                        @if (row.const_pago) {
                          <div class="pt-2">
                            <span class="text-[10px] font-bold uppercase tracking-wider text-slate-400 bg-slate-900 border border-slate-800 px-3 py-1.5 rounded-lg">
                              Nro. Constancia Pago: <span class="text-white font-mono ml-1">{{ row.const_pago }}</span>
                            </span>
                          </div>
                        }
                      </div>

                      <!-- Col 2: Bank and Conformidad details -->
                      <div class="space-y-4">
                        <!-- Bank Document details -->
                        <div class="space-y-1.5 bg-slate-950/20 p-3.5 rounded-xl border border-slate-800/40">
                          <h5 class="text-[9px] uppercase font-bold text-slate-500 tracking-wider">Documento de Banco (Giro)</h5>
                          <p class="text-xs font-bold text-slate-200 truncate">
                            {{ row.nom_doc_b || 'No registrado' }}
                          </p>
                          @if (row.fec_doc_b) {
                            <p class="text-[10px] text-slate-500">
                              Fecha Giro: <span class="text-slate-300 font-semibold">{{ row.fec_doc_b }}</span>
                            </p>
                          }
                        </div>

                        <!-- Conformidad details -->
                        <div class="space-y-1.5 bg-slate-950/20 p-3.5 rounded-xl border border-slate-800/40">
                          <h5 class="text-[9px] uppercase font-bold text-slate-500 tracking-wider">Conformidad Recibida</h5>
                          <p class="text-xs font-bold text-slate-200 truncate">
                            {{ row.confor_doc || 'Pendiente de conformidad' }}
                          </p>
                          @if (row.confor_des) {
                            <p class="text-[10px] text-slate-400 truncate">
                              {{ row.confor_des }}
                            </p>
                          }
                          @if (row.confor_fec) {
                            <p class="text-[10px] text-slate-500">
                              Fecha Conformidad: <span class="text-slate-300 font-semibold">{{ row.confor_fec }}</span>
                            </p>
                          }
                        </div>
                      </div>

                    </div>
                  </td>
                </tr>
              }
            }
          }
        </tbody>
      </table>
    </div>

    <!-- Table Footer / Pagination -->
    <div class="p-4 border-t border-slate-800 bg-slate-900/20 flex flex-col sm:flex-row items-center justify-between gap-4 text-xs font-semibold text-slate-400">
      <div>
        Mostrando registros del 
        <span class="text-white">{{ rows().length === 0 ? 0 : (currentPage() - 1) * pageSize() + 1 }}</span> al 
        <span class="text-white">{{ Math.min(currentPage() * pageSize(), rows().length) }}</span> de 
        <span class="text-white">{{ rows().length }}</span> totales
      </div>

      <div class="flex items-center gap-2">
        <button 
          (click)="changePage(-1)" 
          [disabled]="currentPage() === 1 || loading()"
          class="p-2 rounded bg-slate-850 hover:bg-slate-800 border border-slate-800 disabled:opacity-30 disabled:cursor-not-allowed transition-colors"
        >
          <!-- Chevron Left Icon -->
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2.5" stroke="currentColor" class="h-3.5 w-3.5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 19.5L8.25 12l7.5-7.5" />
          </svg>
        </button>
        
        <div class="px-3 py-1 bg-[#0b1329]/65 border border-slate-800 rounded text-slate-300 font-bold">
          Página {{ currentPage() }} de {{ totalPages() }}
        </div>
        
        <button 
          (click)="changePage(1)" 
          [disabled]="currentPage() === totalPages() || loading()"
          class="p-2 rounded bg-slate-850 hover:bg-slate-800 border border-slate-800 disabled:opacity-30 disabled:cursor-not-allowed transition-colors"
        >
          <!-- Chevron Right Icon -->
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2.5" stroke="currentColor" class="h-3.5 w-3.5">
            <path stroke-linecap="round" stroke-linejoin="round" d="M8.25 4.5l7.5 7.5-7.5 7.5" />
          </svg>
        </button>
      </div>
    </div>
  </div>

</div>
